### ISSUE TITLE
[Tools]Got segmentation fault and illegal instruction while running gsce

### ISSUE THREAD

**Issue by benesse1899** [oscarlab/graphene#1017]
Hi

I was trying to run several docker image through `gsce`, I've tried redis:4.0.0 and r-base.
Both can successfully build the docker image, but they both has problem while running `app_exec`.

In redis:4.0.0, it said:
`/gbin/app_exec: line 7:     7 Illegal instruction     (core dumped) SGX=1 ./redis.manifest.sgx`

and in r-base:
`/gbin/app_exec: line 7:     7 Segmentation fault      (core dumped) SGX=1 ./r-base.manifest.sgx`

I've tried add `GDB=1` before `SGX=1`, and I got this in redis:4.0.0
 `Program received signal SIGILL, Illegal instruction.
0x000000003bcdb85f in ?? ()`
don't know what is this

and r-base got
`Program received signal SIGSEGV, Segmentation fault.
0x0000555555557139 in scan_enclave_binary ()`
I found `scan_enclave_binary ()` is a function in `Pal/src/host/Linux-SGX/sgx_main.c`

Now I'm stopping here because I don't know if there really has problem in `sgx_main.c`.
By the way, my friends also trying this, but they didn't have these problem.

**Comment by dimakuv** [comment]
The GSCE tool is *very* experimental currently. We have plans to re-write it completely and make it more stable. As to your issues, could you run Redis 4.0.0 without Docker (but under Graphene-SGX) and see if the same error happens? You could try the same with R.

The Redis error is suspicious, I've never encountered it. But it may also be because of the say newer Glibc (Graphene only works with Glibc up to 2.27 currently).

The second error may be due to the limitation of GSCE. The tool currently doesn't automatically figure out *all* dependencies of complex apps like R.

**Comment by mkow** [comment]
GSC was deprecated, but there's a new implementation under review, which should be much better: https://github.com/oscarlab/graphene/pull/1345.
I'm closing this issue as outdated.
