### ISSUE TITLE
[Linux-SGX]run ls command fail in bash

### ISSUE THREAD

**Issue by pangzi85480** [oscarlab/graphene#1031]
1. cd LibOS/shim/test/apps/bash
2. make SGX=1 && make SGX_RUN=1
3. ./pal_loader SGX bash.manifest

```
./pal_loader SGX bash.manifest
*** No client info specified in the manifest. Graphene will not perform remote attestation ***

ls
*** No client info specified in the manifest. Graphene will not perform remote attestation ***
*** No client info specified in the manifest. Graphene will not perform remote attestation ***
*** allocating out of heap: 0x8072d5000 ***
shim_init() in do_migration (-13)
Saturation error in exit code -13, getting rounded down to 243
/bin/bash: line 2:     2 Killed                  ls
```

I try to set "sgx.enclave_size = 2G", but also failed.
Maybe it`s a bug of fork()?

**Comment by dimakuv** [comment]
We are currently re-working the bash example. It looks like you're hitting the old issue:
- https://github.com/oscarlab/graphene/pull/859
- https://github.com/oscarlab/graphene/issues/826
- https://github.com/oscarlab/graphene-tests/pull/14 (this is especially important for you to understand the root cause)

The simple way to fix your issue is to:
- Put `sgx.enclave_size = 2G` in **all** manifest template files (bash, cat, cp, date, ls, ...).
- Rebuild everything in the bash dir.

**Comment by pangzi85480** [comment]
> We are currently re-working the bash example. It looks like you're hitting the old issue:
> 
> * #859
> * #826
> * [oscarlab/graphene-tests#14](https://github.com/oscarlab/graphene-tests/pull/14) (this is especially important for you to understand the root cause)
> 
> The simple way to fix your issue is to:
> 
> * Put `sgx.enclave_size = 2G` in **all** manifest template files (bash, cat, cp, date, ls, ...).
> * Rebuild everything in the bash dir.

Thank you, I tried it as you said, but it still failed.

**Comment by dimakuv** [comment]
Does it fail in exactly the same way? What kind of additional info you see when you enable `loader.debug_type = inline`?

**Comment by pangzi85480** [comment]
> Does it fail in exactly the same way? What kind of additional info you see when you enable `loader.debug_type = inline`?

I changed the host from centos to ubuntu, bash and ls are all working fine.
thank you very much.
