### ISSUE TITLE
LibOS and -O2 causes failure of libos regression test on Linux-SGX

### ISSUE THREAD

**Issue by yamahata** [oscarlab/graphene#1040]
Now LibOS is compiled with -O0 (default).
With -O2 enalbed, Linux-SGX libos regression test fails. 
LibOS regression test on Linux, Linux-18.04, Linux-SGX-18.04 succeed. Also with gcc-8, it succeeds. (with #1039 applied)

Ubuntu 16.04 has gcc-5.4. Since it's old, it may not be worthwhile to investigate it. 
We can switch to 18.04.
Thoughts?

options:
- disable -O2 if gcc 5
- drop 16.04 support
- won't try -O2

**Comment by mkow** [comment]
4. fix the underlying UB?

IMO most likely this is caused by some UB in our code (we have tons of those), not a GCC bug. The old GCC just compiled our code differently, exposing the bug.

**Comment by dimakuv** [comment]
For now, I would go with `disable -O2 if GCC 5` and a warning message. If anyone has cycles, it would be good to investigate the root cause of these failures.

**Comment by dimakuv** [comment]
Ok, I can hit the same bug on my local machine. Debugging right now... (I hit the same bug while doing https://github.com/oscarlab/graphene/pull/1084).

**Comment by dimakuv** [comment]
So this one is interesting. I don't understand the exact cause, but it has to do with the fact that `sgx_thread.c` uses Pthread functions instead of raw syscalls (compare with Linux-Pal's `db_threading.c`).

This was to be expected, actually. The LibOS and PAL code should not use POSIX functions like `pthread_*` but instead must rely solely on raw syscalls. I guess the reason to use `pthread_*` in SGX PAL was historical, since it was easier/faster to implement for the Graphene-SGX prototype.

It's high time to remove this dependency on `pthread_*`. I will probably do it tomorrow.

**Comment by dimakuv** [comment]
This was a cool bug!

The bug happened because `shim_clone.c: clone_implementation_wrapper()` called `object_wait_with_retry() / DkObjectClose()` before actually setting up a proper in-enclave TCB. The root cause is: (1) the newly created thread has in-enclave FS segment register == 0 because SGX has `TCS.OFSBASGX` and our Graphene-SGX doesn't set up in any way, so `in-enclave FS reg == TCS.OFSBASGX == 0`. (2) `object_wait_with_retry()` checks `PAL_NATIVE_ERRNO` which is implemented via TCB and `mov %fs:<offset>`. (3) but `%fs == 0` so there is a SIGBUS while executing `mov %fs:<offset>`.

I am very surprised that this error manifests only with GCC 5.4.0 and only with -O2. It looks like in other cases, for some reason, address `0x0` is somehow mapped inside of the enclave (or at least doesn't lead to immediate SIGBUS).

The fix is part of #1084.

As a side-effect, I updated Linux-SGX to *not* use `pthread_*` and will submit it as a separate PR. Funny that my initial suspicion on two pthread libs colliding somehow (one in enclave and one on untrusted host) was incorrect. But I already changed the code, so I'll submit a PR.
