### ISSUE TITLE
Question in func file_map

### ISSUE THREAD

**Issue by lackan** [oscarlab/graphene#107]
Hi,

I have a question about why https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_files.c#L238 should minus map_start. Can you explain something?

Thanks,
lackan

**Comment by donporter** [comment]
Hi @lackan, the issue is that trusted files are hashed and checked in 16 KB chunks.  So this line:

https://github.com/oscarlab/graphene/blob/ce49dcb03d263e40af9ac2dd37015dfb702815b9/Pal/src/host/Linux-SGX/db_files.c#L221

expects each chunk to be padded.  If offset isn't a multiple of the chunk size, then the start of the untrusted mapping can be padded down.

As an example, consider the case where you are mapping from offset 17K.  Here, the pal will start mapping umem at 16K (not zero, as the first 16K are not needed).  So, at the line in question, you want to add the difference (1K) to the starting pointer for umem.

Does this make sense?

**Comment by lackan** [comment]
Hi @donporter , thanks, I understand now.
