### ISSUE TITLE
openjdk8

### ISSUE THREAD

**Issue by fixerivan** [oscarlab/graphene#1152]
trying to run a java app with openjdk8 / ubuntu 16.04

set memory limits via -Xms1536m -Xmx1536m while the enclave memory is set to sgx.enclave_size = 4G

interestingly java dies while trying to:

[    33] mmap: user specified address 0x80200000 with length 32210157568 not in allowed user space, ignoring this hint

Error occurred during initialization of VM
[    33] ---- return from shim_write(...) = 43
[    33] ---- shim_write(1,0x2895f8b8,57) ... write
Could not reserve enough space for 31455232KB object heap

i noticed there were some references to running java stuff in the wiki, but are deleted / not accessible anymore

**Comment by dimakuv** [comment]
`with length 32210157568` = 32GBs. It looks like there is an integer overflow error somewhere in Graphene. Could you run your example with `loader.debug_type = inline` in the manifest and attach all the output?

Also, could you put the exact command that you run (+ the manifest) here, so we can reproduce?

**Comment by claudiavmbrito** [comment]
Hi! could you redirect me to openjdk8 example? I'm not finding it anywhere. 
Thanks

**Comment by dimakuv** [comment]
@claudiavmbrito We don't have a Java example. We haven't tested any JVM yet.

**Comment by claudiavmbrito** [comment]
@dimakuv  And could you tell me what would be the main issues of using any JVM with Graphene?  It seems that the memory usage could be an issue as well as all the system calls a simple hello world program needs.

**Comment by dimakuv** [comment]
@claudiavmbrito Yes, these will be the main issues.

1. Patterns of memory usage. JVM will probably hog memory. Also, JVM will probably have some requirements on fixed memory ranges. Some applications (JMV among them) like to reserve some predefined memory range, e.g. `0x200000 - 0x400000`. Since SGX enclaves restrict the enclave memory range, this can lead to problems in Graphene. Currently, these are hard to impossible to resolve...

2. Supported system calls. JVM is a huge codebase, it probably uses some syscalls and syscall flags not supported by Graphene (well, maybe not).

3. Performance. JVM is optimized for "normal" environments. SGX enclaves are by no means "normal", so expect significant performance drop.

**Comment by dimakuv** [comment]
@claudiavmbrito Check this out to solve issue (1): https://mkyong.com/java/java-what-is-xms-and-xmx-parameter/.

**Comment by claudiavmbrito** [comment]
@dimakuv I was actually been trying to work around the first issue with that, seems to me that it is possible to overpass it if we just set our variables correctly.  Which may be a challenge by itself. 
- The second issue has yet to arise in my preliminary tests, however it may be an further on the road (or not, I will hope for the second one though)
- Regarding the third issue, yes, that is a real problem, however, SGX has proven to be a good resource for secure computation and that may be a good trade-off.

I will try to develop an example in a few days, an Hello world one, and be back to you. 
Thanks for the replies ! 👍

**Comment by mkow** [comment]
I think this is outdated, AFAIK OpenJDK should work under current version of Graphene. Feel free to reopen if the issue is still present actually.
