### ISSUE TITLE
Our locks should be assertable

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#1216]
Our lock/spinlock callsites could benefit greatly from being able to assert state of a particular lock (like `assert(is_lock_held(&lock))`. Unfortunately our spinlocks doesn't allow for this currently.

It should be also possible to assert whether a particular lock is held by *us* exactly, not any other thread. Sample PR where this would be useful: #1164.

**Comment by boryspoplawski** [comment]
I see a few ways we can achieve this:

1. Use a simple `is_held` function that only checks if a lock is really taken. This has a big limitation that we do not know *who* really took this lock.
2. Use more advanced version that (in debug builds only) would account for who really took a lock and allow for asserting on that (e.g. a function that checks if we hold this lock). I see no way to implement this in general case, but for LibOS only usage we could use thread ids (easily obtainable in LibOS).
3. Use an external tool for static analysis. Good example would be [sparse](http://man7.org/linux/man-pages/man1/sparse.1.html) which is used by the Linux kernel and allows for, among others, annotating functions with attributes and statically checking for correctness. For example: [this](https://elixir.bootlin.com/linux/latest/source/include/linux/compiler_types.h) defines set of attributes that can be used to annotate that a function takes a lock or must be called with one taken.
4. Use something built in a compiler. I'm not aware of anything in gcc, but clang does have such [an extension](https://clang.llvm.org/docs/ThreadSafetyAnalysis.html). Note that it says that it's a C++ language extension, but it should work also in C (and original whitepaper mentions that). Unfortunately, this would require building graphene on clang ...

I would prefer option 4 if there are plans to build on clang (potentially implementing 1 as it should be trivial, few lines commit) or 3 otherwise.

**Comment by boryspoplawski** [comment]
NB `__user` annotations in the Linux kernel are checked with sparse, which could be useful in graphene as well

**Comment by dimakuv** [comment]
I like 1 and some time in the future 3.

**Comment by boryspoplawski** [comment]
#1251 Implements 1 in PAL and 2 in LibOS
Leaving this open as a reminder for 3

**Comment by boryspoplawski** [comment]
Note to myself: expand this to LibOS locks as well
