### ISSUE TITLE
[LibOS] Need some error handling for IPC and Async helper threads

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#1249]
There are two helper threads created by Graphene:
- Async helper: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/shim_async.c
- IPC helper: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/ipc/shim_ipc_helper.c

These threads do not have "users", and therefore they do not have proper error handling (they cannot return an error code to the "user" because there is no "user" for these threads). This is mostly for `malloc()` error handling. Couple places for example:
- https://github.com/oscarlab/graphene/blob/786b10a00f4636fa042bf1591f3fe666c061830a/LibOS/shim/src/shim_async.c#L77
- https://github.com/oscarlab/graphene/blob/786b10a00f4636fa042bf1591f3fe666c061830a/LibOS/shim/src/shim_async.c#L175
- https://github.com/oscarlab/graphene/blob/786b10a00f4636fa042bf1591f3fe666c061830a/LibOS/shim/src/ipc/shim_ipc_helper.c#L652

We need to add some form of error handling. Two options:
1. Exit only the helper thread via `DkThreadExit()` and write some debug message.
2. Exit the whole process via `DkProcessExit()` and write some debug message.

**Comment by mkow** [comment]
I think we should go for the second option, the first will probably just hang the whole process? (in the typical case, because something was waiting for a job done by this helper)
Also, OOM is something that is rather unrecoverable and the only thing we can do is to exit with an error logged (instead of crashing or hanging).
