### ISSUE TITLE
xsavec

### ISSUE THREAD

**Issue by thomasknauth** [oscarlab/graphene#1252]
While experimenting with PyTorch on Graphene-SGX, I ran into an issue with the xsavec instruction. glibc's rtld has several variants of a function to resolve dynamic functions. One of them is _dl_runtime_resolve_xsavec(). As the name suggests, it uses xsavec to stow away the processor's execution context. For some reason, the space calculated by glibc to hold the xsavec state seems to be insufficient, leading to a stack corruption.

A work around is to disable glibc's use of the xsavec variant by setting the environment variable GLIBC_TUNABLES to `glibc.tune.hwcaps=-XSAVEC_Usable`.

**Comment by dimakuv** [comment]
From offline chat, @thomasknauth discovered the root cause:

This is forcing the subleaf to zero in those cases: https://github.com/oscarlab/graphene/blob/7ec27bad56a29a541d8578cfbe61630761ac280f/Pal/src/host/Linux-SGX/db_misc.c#L157 This seems to cause problems. It breaks glibc in interesting ways. glibc uses `cpuid leaf 0xd` and its subleaves to determine the size to set aside for `xsave[c]`. By forcing the sub-leaf to zero, you basically return garbage to glibc and hell breaks loose.
