### ISSUE TITLE
[Graphene-SGX] Why have two independent base addresses?

### ISSUE THREAD

**Issue by vahldiek** [oscarlab/graphene#1380]
Hi,

I came across an application which starts PIE executables via fork/exec, but itself is non PIE. As a result, you have to specify sgx.static_address=1 in the PIE executable's manifest, otherwise the memory layouts are not compatible and it fails during fork. After chatting with @dimakuv we may want to discuss removing the differentiation and instead only use one base address for the enclave. The respective code can be found in [sgx_main.c](https://github.com/oscarlab/graphene/blob/8d76f9d3fb221a71f972461319e0179a823a5876/Pal/src/host/Linux-SGX/sgx_main.c#L300).

Is there a good reason to keep this differention? Otherwise, I'd suggest to remove the option of static_address from the manifest, the if/else branch in sgx_main.c, and change the pal_sgx_sign to not consider this option as well.

Happy to hear any concerns.

**Comment by mkow** [comment]
So, you mean making everything effectively non-PIE? Doesn't sounds good, security-wise.

How hard would it be to fix the underlying problem with memory layouts? I don't remember what was the problem here.

**Comment by dimakuv** [comment]
The annoying issue is this these lines of code basically: https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_main.c#L300

```c
    if (get_config(enclave->config, "sgx.static_address", cfgbuf, sizeof(cfgbuf)) > 0 && cfgbuf[0] == '1') {
        /* !!! this sets enclave base address to 0x0 */
        enclave->baseaddr = ALIGN_DOWN_POW2(heap_min, enclave->size);
    } else {
        /* !!! this sets enclave base address to 0x800000000 */
        enclave->baseaddr = ENCLAVE_HIGH_ADDRESS;
        heap_min = 0;
    }
```

And this `sgx.static_address` manifest option is derived from whether the executable is PIE or non-PIE. So different executables will have `sgx.static_address = 0` or `sgx.static_address = 1`.

But such executables become incompatible because of our (not amazing) checkpointing implementation. The checkpoint *must be* restored at the exact same addresses in the child enclave, but if the child enclave starts at a completely different address, the checkpoint restore fails!

**Comment by vahldiek** [comment]
In addition, there is actually no ASLR going on here. In both cases the addresses are hard-coded, either 0 (first case) or ENCLAVE_HIGH_ADDRESS. (1 bit randomness).

I agree that ASLR'd memory layout would provide stronger security against some attacks, but this implementation, not matter what wouldn't prevent these attacks. Instead of having one large PR for ASLR'd memory layout, maybe we could break it down into two or three.

**Comment by dimakuv** [comment]
**Decision**: In the meeting, it was agreed to simply change the checkpointing implementation such that no app-specific memory areas are sent/received on `execve()` (it is meaningless anyway). So, this problem will go away, and we can still have `sgx.static_address = 0|1`.

**Comment by dimakuv** [comment]
Update to my last comment.

What I wrote is incorrect. In fact, the emulation of `execve()` does *not* checkpoint any VMAs (see `shim_exec.c: BEGIN_MIGRATION_DEF(execve)`). So this part is already correct.

However, `fork()` *requires* checkpointing of all VMAs. Since we cannot predict whether there will be an `execve()` after the fork, we cannot skip VMA checkpointing. So I don't see how we can simplify the `fork + execve` pattern.

Interestingly, it may be possible to optimize `vfork()` case. Currently it is emulated as `fork()`. However, we cam assume that `vfork()` will use only the VMA-with-thread-stack and no other VMAs. Thus, we can optimize `vfork()` to be exactly like `fork()` but use its own migration function instead of heavy-weight `BEGIN_MIGRATION_DEF(fork)`. In particular, `vfork()` will have smth like:
```
static BEGIN_MIGRATION_DEF(vfork, struct shim_thread* thread, struct shim_process* process) {
    ... all the same as fork ...
    DEFINE_MIGRATE(thread_stack_vma, NULL, 0); // to find this VMA, can use lookup_vma()
 //   DEFINE_MIGRATE(all_vmas, NULL, 0); // DO NOT MIGRATE ALL VMAS
//    DEFINE_MIGRATE(brk, NULL, 0); // DO NOT MIGRATE BRK REGION
//    DEFINE_MIGRATE(loaded_libraries, NULL, 0); // DO NOT MIGRATE LOADED LIBS
//    DEFINE_MIGRATE(gdb_map, NULL, 0); // DO NOT MIGRATE GDB INFO
}
END_MIGRATION_DEF(vfork)
```

I wonder how often `vfork + exec` (or it's equivalent `clone(CLONE_VFORK)`) is used in real-world apps in comparison to `fork + exec`. If it is used rather often (looks like Glibc prefers it!), then we can have a nice performance gain in multi-process apps.

**Comment by dimakuv** [comment]
After discussing with @vahldiek , we noted that the POSIX standard and Linux *allow* `vfork()` to read (but not modify) all parent's memory. So technically we'll need to copy all VMAs even in `vfork()` case...

I need to think more about `vfork`. Maybe we should re-write it completely so it behaves in a more Linux-based way (pseudo-process in the same address space of the parent process until it `__exit` or `execve`).

**Comment by dimakuv** [comment]
I don't think we can do anything about this issue. We must specify `sgx.nonpie_binary = true` (which is the new name for `sgx.static_address = 1`) in case of multi-process applications where at least one process is non-PIE. It seems that people also don't complain about it. So closing this.
