### ISSUE TITLE
[Graphene] Since Glibc 2.31, system() libc call has different behavior and fails

### ISSUE THREAD

**Issue by vahldiek** [oscarlab/graphene#1381]
The system() libc call has a different behavior between version 2.27 and 2.31. In 2.27, libc called fork and exec to start the shell. In 2.31, it leads to a particular clone call with arguments that Graphene currently does not support. Since master moved to 2.31 last week, this issue is triggered.

```
[     1] ---- shim_clone(CLONE_VM|CLONE_VFORK|SIGCHLD,0x4349eff0,0x439c8740,0x3000000030,0x0) ... clone
[     1] clone called with unsupported flags argument.
[     1] ---- return from shim_clone(...) = -22
```

To trigger this issue call `python` with `-c 'import os;os.system("ls")'`. The error occurs in [shim_clone.c](https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/sys/shim_clone.c#L194). It is supposed to be handled by the first condition check (VFORK), but due to its arguments being non-NULL, it faills. A simple removal of the non-NULL checks does not resolve the issue. 

I will look into this issue closer next week. Just a heads up, if someone currently uses glibc 2.31 and system().

**Comment by dimakuv** [comment]
This is a very cool bug. Here is a description of why it happens.

1. `system()` POSIX function call is implemented via `__posix_spawn()` in Glibc 2.31:
https://elixir.bootlin.com/glibc/glibc-2.31/source/sysdeps/posix/system.c#L147
2. `__posix_spawn()` through a couple of indirections calls `__spawnix()`. This function in turn calls `CLONE()`/`__clone()`: https://elixir.bootlin.com/glibc/glibc-2.31/source/sysdeps/unix/sysv/linux/spawni.c#L382.
3. Finally, `__clone()` assembly calls `syscall(clone)`: https://elixir.bootlin.com/glibc/glibc-2.31/source/sysdeps/unix/sysv/linux/x86_64/clone.S#L76. At this point, it is intercepted by Graphene.
4. The `clone()` syscall is called as `shim_clone(CLONE_VM|CLONE_VFORK|SIGCHLD, /*user_stack_addr=*/0x2e774d0d8ff0, ...)`. The important part here is the non-NULL child stack!

Graphene had a special case for such VFORKs in `shim_clone.c`. The code looks like:
```c
    /* special case for vfork. some runtime uses clone() for vfork */
    if (flags == (CLONE_VFORK | CLONE_VM | SIGCHLD) &&
        user_stack_addr == NULL && parent_tidptr == NULL &&
        child_tidptr == NULL && tls == NULL) {
        return shim_do_vfork();
    }
    ... since user_stack_addr is not NULL, Graphene goes further ...
```

At this point, we tried to ignore the `user_stack_addr` argument and simply do:
```c
    if (flags == (CLONE_VFORK | CLONE_VM | SIGCHLD) {
        return shim_do_vfork();
    }
```

But this failed in mysterious ways.

What happens in reality is very interesting. Glibc 2.31 code allocates a child stack on the heap (https://elixir.bootlin.com/glibc/glibc-2.31/source/sysdeps/unix/sysv/linux/spawni.c#L350). Importantly, Glibc's `clone()` wrapper puts `fn()` and `argv` for the new process on this child stack (https://elixir.bootlin.com/glibc/glibc-2.31/source/sysdeps/unix/sysv/linux/x86_64/clone.S#L59). After `clone()`, the child process jumps out of the syscall, pops the function pointer and the arguments from this child stack and calls this func (https://elixir.bootlin.com/glibc/glibc-2.31/source/sysdeps/unix/sysv/linux/x86_64/clone.S#L93).

However, Graphene always assumes that `clone()` in the child process returns on the same (parent) stack (see `shim_do_clone()` and `restore_context()`). Therefore, restored RSP in the child does *not* point to the child stack but instead points to the parent stack. Now Glibc's `clone()` wrapper tries to pop `fn` and `argv` from the current stack -- but it is the parent stack! So some garbage from the parent stack is taken, and Glibc ends up calling into some random code segment. After this, Graphene fails in funny ways.

A way to fix this is to temporarily rewire the current thread (the one issuing `clone(VFORK, ...)`) so that it points to the provided child stack `user_stack_addr`, and rewire it back to original parent stack after the clone (only in the parent process of course). The child process will resume execution with the correct child stack, whereas the parent will not notice any difference.

The PR with this solution is https://github.com/oscarlab/graphene/pull/1384.

P.S. Previous Glibc versions had a different way of implementing `system()` and that's why this bug was not triggered before. In particular, see the implementation of `do_system()` in Glibc 2.27 (https://elixir.bootlin.com/glibc/glibc-2.27/source/sysdeps/posix/system.c#L116).
