### ISSUE TITLE
Job control by outside from graphene process isn't handled well

### ISSUE THREAD

**Issue by yamahata** [oscarlab/graphene#1418]
The was recorded in wiki page. But now our wiki was disabled. So I record it as an issue.

## Description of the problem:
Job control from outside of graphene isn't handled well.

Problem:
Currently graphene isn't aware of signal sent from outside of graphene. It is necessary to define how graphene process should interact with the outside of graphen world and implemet such behaviour in the context of job control and unix signal.

50ca6c4a2 solved the following issue.
- [x] The signal is simply handled by the received thread. 
- [x] graphene internal thread may eat up the signal instead of propagating to the app. graphene should propagate such job-control signal to the app.
- [x] When the signal is sent to a process and the receiving thread masked the signal, graphene should search other app thread that doesn't mask it and deliver the signal to that thread. But the current implementation totally lacks such logic.

Use case:
- systemd(or sysv init scripts), kubenetes or other job management system:
  - they creates graphene processes and terminates by sending signal to managed processes. Usually SIGTERM and then after timeout, SIGKILL
     - systemd: SIGTERM, SIGKILL, SIGHUP, SIGQUIT, SIGABRT.
     - kuberenetes: SIGTERM, SIGKILL (it's user customizable which signal to be used )
  - SIGHUP (or other signal) to tell servers to reload configuration.
- from keyboard
  - C-c: SIGINT
  - C-z: SIGSTOP, SIGCONT
  - C-\\: SIGQUIT
- terminal control: SIGTTIN, SIGTTOU, SIGWINCH
  - feedback needed: probably terminal control can be out of scope because job in enclave usually isn't user-interactive. Is this true?
- session and process group
  - signal can be sent to a process group. At the moment, graphene is ignorant of session and process group which observed by outside of graphene.

**Comment by boryspoplawski** [comment]
> Currently graphene isn't aware of signal sent from outside of graphene.

This is an old issue, but this is still the case and that's by design.

> Use case:

>     * systemd(or sysv init scripts), kubenetes or other job management system:
>       
>       * they creates graphene processes and terminates by sending signal to managed processes. Usually SIGTERM and then after timeout, SIGKILL

This is actually the only case that we support. There is a special manifest entry that enables one-time injecting of SIGTERM just to handle graceful exits.

>         
>         * systemd: SIGTERM, SIGKILL, SIGHUP, SIGQUIT, SIGABRT.
>         * kuberenetes: SIGTERM, SIGKILL (it's user customizable which signal to be used )
>       * SIGHUP (or other signal) to tell servers to reload configuration.

This are not supported and are not meant to be. In general case being able to arbitrarily inject signals could be a security issue. If your use case really needs that, you can always write a wrapper program, which spawns target app and sends some signals to it e.g. depending on some stdin or socket input.
Btw SIGKILL is not catchable.

>     * from keyboard
>       
>       * C-c: SIGINT
>       * C-z: SIGSTOP, SIGCONT
>       * C-\: SIGQUIT

That's only useful for manual testing of some shell interactive sessions, otherwise it could be a security issue (see above).

>     * terminal control: SIGTTIN, SIGTTOU, SIGWINCH
>       
>       * feedback needed: probably terminal control can be out of scope because job in enclave usually isn't user-interactive. Is this true?

I don't see any difference between these and those input from keyboard / generic signal injection (see above).

>     * session and process group
>       
>       * signal can be sent to a process group. At the moment, graphene is ignorant of session and process group which observed by outside of graphene.

Internal process group support is not done at the moment, as we have not yet had any use cases for it and it would require non-trivial changes (but it's doable if the need arises). Host level process groups are ignored and always will be (why wouldnt it?).


Let it be noted that all of the above will work correctly is everything is running inside a Graphene instance, i.e. all those signals are sent internally in Graphene.
