### ISSUE TITLE
question about making graphene+sgx docker image

### ISSUE THREAD

**Issue by justalittlenoob** [oscarlab/graphene#1513]
I've made a graphene+sgx docker image(by `docker commit`. isgx and gsgx drivers are installed on the host machine, sgx sdk/psw and graphene are installed in the image), which an run graphene/Examples successfully.   

The problem is the image is too big for me (about 1.8G). So i am wondering that if sgx sdk/psw and graphene can only be installed on the host machine (just like isgx and gsgx driver), and mounted into the container? If so, which files need to be mounted or copied into container? It would be great if there was an example for reference.

Any advice would be appreciated.

**Comment by dimakuv** [comment]
@vahldiek Could you reply to this question?

**Comment by vahldiek** [comment]
Thanks for pointing me to this question!

The Intel SGX sdk/psw is not required to be installed in the Docker image. Instead simply mount the devices which are required in your Docker run command.
``` sh
docker run --device=/dev/gsgx --device=/dev/isgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket imagename
```
(You may have to replace `isgx` with `sgx` depending on your driver.

To reduce the image size further, I would suggest to look at the [Graphene Secure Container PR](https://github.com/oscarlab/graphene/pull/1430) which relies on a multi-stage build to reduce the required Graphene files to the runtime. In particular, take a look at the [second stage](https://github.com/oscarlab/graphene/blob/191f6550c2c144f9fe3a86df27c8844c795d3485/Tools/gsc/templates/Dockerfile.ubuntu18.04.gscapp.template), since it copies the relevant files from the [first stage](https://github.com/oscarlab/graphene/blob/191f6550c2c144f9fe3a86df27c8844c795d3485/Tools/gsc/templates/Dockerfile.ubuntu18.04.template).

**Comment by justalittlenoob** [comment]
@vahldiek That's what i'm looking for. Thank you very much:)

**Comment by justalittlenoob** [comment]
@vahldiek    
How to add proxy when using gsc build image? For example,    
A gsc command with no proxy, it should like  
`./gsc build hello-world:latest test/ubuntu18.04-python.manifest`   
right?

How to add proxy to the command? I tried 
`./gsc build --env http_proxy --env https_proxy hello-world:latest test/ubuntu18.04-python.manifest`
and 
`./gsc build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy  hello-world:latest test/ubuntu18.04-python.manifest`
but all failed.

**Comment by vahldiek** [comment]
There are several options. GSC itself currently does not provide such configuration options. Instead you could add configuration to ~/.docker/config.json which changes the global behavior of all docker containers started with this configuration file. This file allows to specify a proxy and so on.

In case you prefer a different option, you will have to change [gsc.py](https://github.com/oscarlab/graphene/blob/60d5c8c1676261aa28c45207ec06bd95cff583d6/Tools/gsc/gsc.py#L207) to specify build arguments and network definitions. See the [Python Docker API](https://docker-py.readthedocs.io/en/stable/api.html) for details.

FYI, build args are on the list of future features for GSC.

**Comment by justalittlenoob** [comment]
@vahldiek   
Thanks for your detailed advice. For my situation, both proxy and network are necessary. I can set proxy through `~/.docker/config.json`, but how to set the network(e.g. `--net=host`)?

**Comment by vahldiek** [comment]
Yes. You may provide a ``network_mode`` to the build command in [gsc.py](https://github.com/oscarlab/graphene/blob/60d5c8c1676261aa28c45207ec06bd95cff583d6/Tools/gsc/gsc.py#L207).

**Comment by justalittlenoob** [comment]
@vahldiek Ok, i got it. Thank you so much:)
