### ISSUE TITLE
Interactive mode proposal

### ISSUE THREAD

**Issue by dayeol** [oscarlab/graphene#1618]
I want to be able to receive additional information after I started Graphene.
For example, Graphene starts building the enclave but waits until some further information,
and then finishes initialization once the information arrives.
This will be useful for may use cases as we can control the enclave's lifecycle more dynamically.

To kick off the discussion, I want to propose a new command-line option for pal loader.
With that, you can start Graphene with interactive mode, e.g.,
```
pal-Linux-SGX interactive app.manifest
```
and then Graphene starts off a local web API server.
Now, the user can send requests to the API server to control the enclave lifecycle. e.g.,
```
GET /create HTTP/1.1
```
creates the enclave with `ECREATE` and
```
GET /load HTTP/1.1
```
loads the pages and so on.

The actual interface needs more discussion, but the basic idea is that we can pass in more information along with the HTTP request, e.g., CONFIGID or additional manifest, etc.

Please comment!

**Comment by dimakuv** [comment]
I agree with the command-line option to specify that the user wants to start Graphene in interactive ("wait-for-request") mode.

Note that we shouldn't introduce such an option to the manifest file because then it will be confusing: what does this option (say `sgx.interactive = 1`) mean for forked/execve'd processes? The only time we want to start this interactive mode is when we start the first process in Graphene.

**Comment by mkow** [comment]
I think this shouldn't be a manifest option, as manifests are signed, but this option should be overridable - if I understand correctly, everything it does happens on the untrusted side.

btw. Before we do any smaller changes to the interface I'd prefer to first resolve #1053 (and probably consider this request there).
btw2. Why do you need such a feature, exactly? Is this something for debugging or production needs?

**Comment by dimakuv** [comment]
> btw2. Why do you need such a feature, exactly? Is this something for debugging or production needs?

Since I work with @dayeol, I can answer this. We are currently looking into tweaking Graphene to FaaS workloads. Basically, we want to explore how to "pre-heat" the enclave for the workload (say, start Python and import all typically used modules) and then run the workload on a particular request.

Of course, we can do it at the app level (above Graphene). But we are also exploring if stopping Graphene somewhere in the middle of the init process also helps.

**Comment by mkow** [comment]
Hmm, sounds like freezing it _between_ requests would make more sense? I'm not sure if doing this during initialization has any advantages for your use-case.

**Comment by dimakuv** [comment]
> Hmm, sounds like freezing it between requests would make more sense?

Yes, it makes sense and we're looking into this as well. Freezing between requests doesn't require any changes to Graphene. Or at least it will require only non-intrusive changes (which doesn't deserve an issue on GitHub). This issue is only to gather ideas how to specify that Graphene needs to be run in some kind of interactive mode (to pause at certain places).

**Comment by mkow** [comment]
But if you _only_ want to freeze during app execution (e.g. between requests), but would you need such an interface on Graphene level? As you said, this will be implemented in the app code itself.

**Comment by dimakuv** [comment]
So we're thinking of the following scenario in this issue:
1. Create the enclave with ECREATE and populate with EADD/EMEASURE.
2. Pause right before EINIT.
3. Wait for client request. If there are any special requirements for this request, add more EADD/EMEASURE. Also, change SIGSTRUCT bits if needed.
4. Do the final EINIT.

This way, the client request receives a more targeted MRENCLAVE and other bits during remote attestation. At the same time, it happens slightly faster (we plan to couple this with "preloaded" read-only files added with EADD).

**Comment by mkow** [comment]
Ok, so this will be much more complex API than just freezing during initialization, but also control over what is loaded and how. Seems complex.
btw. I don't think HTTP is a good choice for this, maybe @woju could suggest something better suited?

**Comment by dimakuv** [comment]
Yes, I agree that HTTP/REST protocol is way too complicated... But other than these, I only know Redis binary protocol (https://redis.io/topics/protocol). Let's wait for Wojtek's recommendation.

**Comment by mkow** [comment]
@dimakuv is this something you're still investigating? Sounds like a quite complex feature, I'm against implementing it if there's no strong justification for it.

**Comment by dimakuv** [comment]
We can close this issue for now. We (=Intel Labs) are still interested in this idea, but we have no time/people to work on this. Anyway, the discussion died in this thread :)
