### ISSUE TITLE
Is power 2 size reasonable when enclave size is larger than 16GB

### ISSUE THREAD

**Issue by qiyuangong** [oscarlab/graphene#1651]
Just a question about this check:
If my application requires 20GB memory, it seems that I have to apply for 32GB EPC.  If my application requires 33GB, then I have to apply for 64GB.

That's a huge waste of EPC. :)

**Comment by mkow** [comment]
Enclave size is _not_ the same as EPC size, EPC is only a cache for current working set. Enclave size is the virtual memory address range dedicated for an enclave. The size of this range must be a power of 2, which is required by SGX hardware.

Having said this, I don't remember if the whole range has to be measured at start or if this is only Graphene's peculiarity. @dimakuv will know ;)
Also, this issue doesn't exist on HW supporting EDMM (modulo Graphene's lack of support for this... ;) )

**Comment by dimakuv** [comment]
@mkow is right. The application requires say 32GB of *virtual memory*. It will be backed by EPC which you can think of as *physical memory* of your machine. So a machine with say 128MB of EPC can still run 32GB enclaves.

The enclave memory has to be size of *power of 2*: this is a HW requirement (it is easier to implement memory-range checks in MMU this way, boils down to bit twiddling). So you're right that an application with 33GB of working set size requires 64GB-sized enclave. This limitation is atypical in software, but quite common in hardware.

Graphene does *not* measure (with EEXTEND instruction) all application memory at the start: everything except the heap is measured (executable, BSS, stacks, manifest). However, currently Graphene *zeroes out* the heap (because it wasn't measured so needs to be predictable). This zero-out of the heap takes a long time, especially if you try to create a huge enclave. We will actually fix this behavior, so the startup times will become much lower: https://github.com/oscarlab/graphene/pull/1640.

**Comment by qiyuangong** [comment]
Thank you @mkow @dimakuv for details explanation. :)

Now I understand the difference of EPC and enclave size, and the reason of power of 2 limitation.

Issue closed.
