### ISSUE TITLE
nodejs 12 crashes on Assertion `(uv_loop_init(&tracing_loop_)) == (0)'

### ISSUE THREAD

**Issue by kim0** [oscarlab/graphene#1652]
## Steps to reproduce

* Install nodejs-12 on Ubuntu 1804, per these instructions https://github.com/nodesource/distributions/blob/master/README.md#debinstall
* Try to run the example, nodejs crashes on an assertion as below
* graphene git commit 3323d214442a1f546a2d7b2a06e5b8128d0d8cbc

## Expected results
nodejs runs

## Actual results
```
$ SGX=1 ./pal_loader nodejs.manifest helloworld.js
WARNING: Using insecure argv source. Don't use this configuration in production!
nodejs[1]: ../src/tracing/agent.cc:55:node::tracing::Agent::Agent(): Assertion `(uv_loop_init(&tracing_loop_)) == (0)' failed.
 1: 0xa0bb60 node::Abort() [nodejs]
 2: 0xa0bbde  [nodejs]
 3: 0xae9afa node::tracing::Agent::Agent() [nodejs]
 4: 0x9dc3ea node::InitializeOncePerProcess(int, char**) [nodejs]
 5: 0x9dc9f3 node::Start(int, char**) [nodejs]
 6: 0x2f135d6d __libc_start_main [/lib/libc.so.6]
 7: 0x979215  [nodejs]
```

**Comment by dimakuv** [comment]
I can reproduce it on Ubuntu 18.04 and the latest master. Need to debug...

**Comment by pwmarcz** [comment]
This is because libuv [needs eventfd](https://github.com/nodejs/node/blob/v12.19.0/deps/uv/src/unix/async.c#L210), which we [disallow by default](https://graphene.readthedocs.io/en/latest/manifest-syntax.html#allowing-eventfd) because the current implementation is not secure and proxies calls to a native eventfd. Adding `sys.insecure__allow_eventfd = 1` seems to work.

Unfortunately this is the same for newer Node versions. Before Node 12, [libuv handled systems without eventfd](https://github.com/nodejs/node/blob/v11.x/deps/uv/src/unix/async.c#L230) by checking for ENOSYS. But [they dropped that in February this year](https://github.com/libuv/libuv/commit/dfd64933d55fee97c329a1c13b5d6dac874e295c) since they don't support Linux versions without it.

I tried Node 10 (oldest supported LTS, until April 2021) but it fails for me with "Fatal process OOM in insufficient memory to create an Isolate". I'm not sure what this is about, [here is the check](https://github.com/nodejs/node/blob/v10.23.0/deps/v8/src/heap/heap.cc#L1622) if you're interested in digging deeper, [the advice about increasing Node heap size](https://stackoverflow.com/questions/54919258/ng-commands-throws-insufficient-memory-error-fatal-process-oom-in-insufficient) doesn't seem to help.

**Comment by dimakuv** [comment]
Thanks @pwmarcz for analysis!

So our node.js example always fails, even with `sys.insecure__allow_eventfd = 1`?

**Comment by pwmarcz** [comment]
No. It does work with `sys.insecure__allow_eventfd` and Node 12 or newer. Sorry if that wasn't clear. 

(I haven't checked SGX though.)

**Comment by omeg** [comment]
I've tried to run [Deno](https://github.com/denoland/deno) in Graphene-SGX recently and run into the same OOM problem. After a quick investigation this seems to be the main culprit:
https://chromium.googlesource.com/v8/v8/+/refs/heads/master/src/init/isolate-allocator.cc#53

**Comment by dimakuv** [comment]
This was fixed.
