### ISSUE TITLE
Upgrade Graphene to work with GLIBC 2.23

### ISSUE THREAD

**Issue by r-kellerm** [oscarlab/graphene#179]
Hi - 
Is there any plan to upgrade Graphene for GLIBC 2.23 (And Ubuntu 16.04 or higher in general)?

Thanks.

**Comment by donporter** [comment]
We use 16.04 for development and testing these days (should probably update the README).  So 16.04 should work.  I don't think there is any objection to higher versions (or accepting patches that fix issues with newer versions of Ubuntu), but it just hasn't been a priority.

I think it works on a host system with glibc 2.23 (in a facile way).  The issue is porting the glibc changes for within graphene to glibc 2.23.

**Comment by r-kellerm** [comment]
Hi,

I'm trying to run an enclavized application (TensorFlow benchmark app) and getting the following error at runtime:
"benchmark: /lib/libm.so.6: version 'GLIBC_2.23' not found (required by benchmark)"
As I understood, this is because the application is linked with glibc of another version that Graphene supports. Is there another way to make it working?

Thank you!

**Comment by donporter** [comment]
Yes, this is because the tensorflow app is compiled against this version of glibc.

The easiest thing to try is recompiling it against glibc-2.19.  It is somewhat unlikely there are actual symbols in .23 that this application relies upon.  

Failing that, the way forward is porting this patch to glibc 2.23.

https://github.com/oscarlab/graphene/blob/master/LibOS/glibc-2.19.patch

**Comment by mkow** [comment]
btw. Would it be possible to just use system's glibc after merging #139 and adding VDSO support?

**Comment by donporter** [comment]
@chiache should confirm the following, but, to document the issues, I believe we patched glibc for a few reasons:

1) redirecting system calls, which #139 would address (but be slower)
2) Adding an entry in TLS
3) Better integration of gdb
4) There are also a few things in glibc commented out (e.g., some time functions) that I don't fully understand why

**Comment by Vampsj** [comment]
@mkow Hi, I have the same problem as you and have you solved it? If you have figured it out, can you tell me about how to compile the python file against glibc-2.19? Thank you.

**Comment by Vampsj** [comment]
@r-kellerm Thank you for your response! It seems it's not trivial to recompile the glibc-2.19 at least for me. Maybe I should also consider about downgrading... Thank you again!

**Comment by donporter** [comment]
Downgrading is certainly going to be easier than the alternative.

**Comment by mkow** [comment]
This was done some time ago in #809.
