### ISSUE TITLE
When application runs as sudo user, SIGINT not received by application, it hangs.

### ISSUE THREAD

**Issue by sudharkrish** [oscarlab/graphene#1890]
## Description of the problem
Seeing an issue with signal handling in SGX mode. Have a simple test program, which has a signal handler(for SIGINT), so if user hits Ctrl-C, it should exit the program.  Issue encountered ONLY when application is run as sudo user, Ctrl-C is not detected, and program hangs

## Expected results
When user hits Ctrl-C, program should receive it, and exit.

## Actual results
Program hangs

The strange thing is, if I add a call to sleep in the while loop, like usleep(100), then hitting Ctrl-C works as expected.

**Comment by sudharkrish** [comment]
Issue seen with graphene commid->1cbdf3225aba04f02c2caca2376edb46235b64e1

Here below is the test code to reproduce the issue.

**Issue seen ONLY when program is run as sudo user.**

```
volatile uint8_t received_signal = 0;

static void sig_handler(int sig_num) {
    printf("Received signal %d\n", sig_num);
    received_signal = 1;
}

int main(int argc, char** argv) {
    /* catch ctrl-c  */
    signal(SIGINT, sig_handler);                                                                              
    printf("Hello world (%s)!\n", argv[0]);
    while (!received_signal) {
        /* NO-OP */
        //usleep(100);
    }   
    printf("Signal received. Exiting while loop \n");
    return 0;
}

```
sudo SGX=1 ./pal_loader helloworld

**Issue seen ONLY when program is run as sudo user.**

**Comment by dimakuv** [comment]
Two things:

1. I fixed a bug in signal handling recently. Please try newer Graphene, at least this commit: https://github.com/oscarlab/graphene/commit/a534cb4b852369fd20c84c049650c89a339659f5. This may or may not help...

2. Why do you want to run Graphene under `sudo`? It's pretty scary due to trivial shell escape. Note that the only blessed way of running Graphene currently is via the `pal_loader` script, which does `exec` of the actual Graphene executable in the end -- and mixing `sudo` and `exec` has weird semantics (and also shooting yourself directly in the foot). Googling `sudo exec` gives many examples.

I think the short answer is: `sudo` and Graphene do not mix well, `sudo` has complicated semantics, don't do it.

**Comment by mkow** [comment]
@sudharkrish ping ^

**Comment by sudharkrish** [comment]
@dimakuv Thanks. I tried the latest graphene, and this issue is no longer there. This PR can be closed. I had to run with sudo, since I am running DPDK application which requires root privileges. There are more than a couple of things to configure, to allow normal user to run DPDK without sudo privilege, I havent set that up yet. Sorry for the late reply, I just saw these comments on this PR.
