### ISSUE TITLE
Why implement epoll using ppoll?

### ISSUE THREAD

**Issue by wangchenghku** [oscarlab/graphene#192]
Hi, I found graphene implemented epoll using `INLINE_SYSCALL(ppoll, ...)` in `db_object.c`. I am curious why you implemented it in this way. ppoll is level triggered, but epoll can be configured with either level triggered or edge triggered. So I really doubt whether this kind of implementation works for both triggering modes.

**Comment by donporter** [comment]
I can't speak to the history, but I think you are right that a generalization of the waiting interface may be to differentiate level and edge-triggered events.  I'm tagging this as a likely missing feature.

**Comment by chiache** [comment]
In my opinion, the edge-triggering epoll feature can be emulated at the library OS level, and it is indeed a missing feature to applications. Regarding why we use ppoll() instead of epoll() to implement the host interface: we choose a polling-based interface because it is generally more portable. Besides, multiple processes (each with a library OS instance) may be polling on the same stream and an edge-triggered host interface can only deliver the event to one of the processes. It is much easier to let each process individually check whether there is any readable data or otherwise simply block until the stream is readable again.

**Comment by donporter** [comment]
@wangchenghku PR #197 should address the second issue (not the overall edge vs. level-triggered issue).  See if it addresses your problems.

**Comment by wangchenghku** [comment]
@donporter Thanks for your reply. I will find a time and test it.

**Comment by wangchenghku** [comment]
Hi, @chiache @donporter I am just testing some Java programs, but there is a missing patch file called `JDK-8015880.patch` in OpenJDK which is required by makefile. Could you possibly fix it? Many thanks.

**Comment by donporter** [comment]
Strange, I also see this issue.  @chiache ?

**Comment by dimakuv** [comment]
Chia-Che replied to the original question. The bug raised by wangchenghku was fixed. I'm closing this issue.
