### ISSUE TITLE
/dev/sgx/enclave is gone in the latest in-tree SGX kernel

### ISSUE THREAD

**Issue by lianhao** [oscarlab/graphene#2007]
Currently, graphene expect to find the **/dev/sgx/enclave** device to open for operations. But the latest [in-tree SGX kernel to be upstreamed](https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/linux-sgx.git) doesn't have that device file anymore, it is renamed to **/dev/sgx_enclave**.

We've worked around this by creating a symbolic link /dev/sgx/enclave to /dev/sgx_enclave, but it would be better for graphene to support this new in-tree kernel too.

**Comment by dimakuv** [comment]
Thank you @lianhao. This looks like an easy fix.

I will create a PR for this tomorrow hopefully.

**Comment by johnvenn** [comment]
hi

I will fix this issue.

**Comment by johnvenn** [comment]
SGX driver is upstreamed to Linux kernel version 5.11+, where the device is exposed as "/dev/sgx_enclave" instead of "/dev/sgx/enclave" as the legacy OOT driver does. This issue could be solved by remapping in-kernel SGX device node to "/dev/sgx/enclave", if you install the latest SGX PSW for aesmd service, the issue could be solved. Also you can manually apply udev rules, refer to:
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/driver/linux/README.kernel.md#udev-rules
