### ISSUE TITLE
How safe is the host from a malicious enclave?

### ISSUE THREAD

**Issue by bio43** [oscarlab/graphene#2023]
The focus of graphene is of course to protect the enclave from the host, but how well protected is the host from the enclave? I.e. can I run untrusted code in the enclave without risking that the host OS is compromised? If not, is there anything that can be done to harden against such an attack vector?

**Comment by dimakuv** [comment]
The SGX enclave is part of a normal Linux process. Everything that the Linux kernel does to isolate itself and other processes from this process equally applies to SGX and to Graphene. There are no particular new attack vectors with SGX/Graphene to attack the kernel.

The only "new" thing is that the kernel cannot peek inside the SGX enclave and decide that the process is suspicious and needs to be killed preemptively. This is a well known issue and can be googled via "malicious SGX enclave". One popular research paper about this: https://arxiv.org/abs/1902.03256 (but please read the whole paper because the authors oversell it in the Abstract).

**Comment by mkow** [comment]
+1 to everything Dmitrii said. Graphene doesn't try to protect host from the app in any way - you need a specialized security sandbox if you want to run untrusted code (e.g. a VM or a Linux namespace sandbox - but please never implement a custom solution for this, it's like with crypto, you should never implement such things on your own).

Ad the malware digression: I don't think there's any reasonable use of SGX in malware except just as an additional obfuscation technique. And I really don't like the paper linked, it's basically "we show you how to get local code execution, assuming you already have local code execution". Running untrusted enclave is like running untrusted code.
