### ISSUE TITLE
Error while building SGX container using GSC

### ISSUE THREAD

**Issue by alexthomas1** [oscarlab/graphene#2188]
Traceback (most recent call last):
  File "./gsc", line 10, in <module>
    from gsc import main # pylint: disable=import-error,wrong-import-position
  File "./gsc.py", line 20
    return f'gsc-{original_image_name}'Traceback (most recent call last):
  File "./gsc", line 10, in <module>
    from gsc import main # pylint: disable=import-error,wrong-import-position
  File "./gsc.py", line 20
    return f'gsc-{original_image_name}'

SyntaxError: invalid syntax

Looks like I am getting some syntax error on latest commit on master: 2decd11ab88d13737e2161f1871b64d9efdf8e95

I am running this on Ubuntu 16.04.7

**Comment by dimakuv** [comment]
This is most probably because your Ubuntu 16.04 has Python version less than 3.6.

The GSC tool now uses Python's f-strings everywhere, and they are only supported in Python starting from v3.6. See https://realpython.com/python-f-strings/. Check e.g. this to install newer Python: https://moreless.medium.com/install-python-3-6-on-ubuntu-16-04-28791d5c2167.

We actually have this requirement in our GSC documentation: https://graphene.readthedocs.io/en/latest/manpages/gsc.html#software-packages.

**Comment by dimakuv** [comment]
Very old inactive issue, closing.
