### ISSUE TITLE
Add recursive directory scan to trusted files

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#2205]
## Description of the problem

It should be possible to add whole directories using `sgx.trusted_files` syntax. Right now all files need to be listed manually, which is very PITA and causes problems if the precise list varies between platforms.

Resolving this will greatly simplify our manifests and make them more portable (e.g. between Ubuntu versions).

**Comment by dimakuv** [comment]
How do you want to implement this? `sgx.trusted_files.walkdir1 = /lib/`? You'll still need hashes of each lib, right (`sgx.trusted_checksums.walkdir1_file001 = ...`)? Won't it bring way too many libraries in the final manifest?

**Comment by mkow** [comment]
I'll just check if the path leads to a dir in `sgx_sign.py`, and if so, then I'll emit entries for all subfiles. Ad too many libs - that's users decision, no one forces you to use the directory version ;) But we have a proper TOML parser, it shouldn't be as slow as the old, handcrafted one.

**Comment by dimakuv** [comment]
Ok, sounds good to me.

**Comment by woju** [comment]
Do you really need to implement this in graphene? I'd move this to jinja templates (#2076), if it would be enough:

```jinja
sgx.trusted_files = [
{% for path in pathlib.Path('/path/to/dir').glob('**/*') %}
    '{{ path }}', {# or maybe some better quoting, idk #}
{% endfor %}
]
```

This would be more flexible, because you'll be able to add some custom filtering, if you don't really want to add all the files.

I've got some preliminary implementation already (d8de596aef4e40f7dd44117f998403a83eadd9d1), and it uses similar construction for `ldd` (https://github.com/oscarlab/graphene/commit/7392b560a696101de283e3a5d3165d881904961d#diff-7693829b9983e7d293f8412b98df3c04c6474ac3fad7152e5f1682c977614a0cR123-R132). I don't have time in Q1 to finish this, but if you'd like to pick up this branch, feel free to do so.

**Comment by mkow** [comment]
> Do you really need to implement this in graphene?

It's 5 lines of Python in sgx_sign.py.
I don't really see any reason why we wouldn't want this. And woju's version requires our manifests to be jinja templates generating TOML to be able to use this.
