### ISSUE TITLE
GSC containers build error

### ISSUE THREAD

**Issue by jurobystricky** [oscarlab/graphene#2229]
## Description of the problem
Building GSC containers is broken:

Seems this commit caused the new error:

[Pal/Linux-SGX] sgx_sign.py: Use proper TOML parser for manifests

I get an error  while building Ubuntu containers:
<pre>
/usr/bin/python3: No module named pip
</pre>

This seems to fix the problem:
<pre>
diff --git a/Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template b/Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template
index 0e1dd04e..b1f16a81 100644
--- a/Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template
+++ b/Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template
@@ -13,6 +13,7 @@ RUN env DEBIAN_FRONTEND=noninteractive apt-get update \
         protobuf-c-compiler \
         python3-protobuf \
         wget \
+       python3-pip \
     && python3 -B -m pip install toml>=0.10
 
 RUN git clone {{Graphene.Repository}} /graphene
</pre>
## Steps to reproduce

<pre>
$ cd graphene/Tools/gsc/test
$ SGXDRIVER_REPO="" SGXDRIVER_BRANCH="" INTEL_SGX_DEVICE="sgx/enclave" ADDITIONAL_DEVICES="" ADDITIONAL_VOLUMES=""  make
</pre>
## Expected results

Build that is not broken

## Actual results

Build broken

**Comment by dimakuv** [comment]
That's because our Jenkins worker that is responsible for GSC testing died and we still haven't replaced it :(

So such tiny errors creep in currently into GSC, because we don't manually test GSC for every change. We should finally move to a normal Jenkins environment.

Let me test locally on my machine and submit a fixing PR. Sorry for this.
