### ISSUE TITLE
No physical memory support, process creation may be slow

### ISSUE THREAD

**Issue by aua237032** [oscarlab/graphene#232]
Hello,

I tried to test `helloworld.c`  in `/LibOS/shim/test/apps/gcc`.
when I run
`make SGX=1`
`make SGX_RUN=1`
`./gcc.manifest.sgx test_files/helloworld.c` 
I got result as below:
`WARNING: no physical memory support, process creation may be slow.
file_map does not currently support writeable pass-through mappings on SGX.  You may add the PAL_PROT_WRITECOPY (MAP_PRIVATE) flag to your file mapping to keep the writes inside the enclave but they won't be reflected outside of the enclave.
file_map does not currently support writeable pass-through mappings on SGX.  You may add the PAL_PROT_WRITECOPY (MAP_PRIVATE) flag to your file mapping to keep the writes inside the enclave but they won't be reflected outside of the enclave.`

And when I run 
`./bash.manifest.sgx bash_test.sh` in  `/LibOS/shim/test/apps/bash` 
I got result as below:
`WARNING: no physical memory support, process creation may be slow.`
When I tried  SGX Quick Start,  I have no problem. I can reproduce this problem only in `/test/apps` directry.
How can I resolve this? I'm sorry that my English isn't very good.

**Comment by dimakuv** [comment]
Hi @aua237032,

You actually see two kinds of messages:

1. A warning "no physical memory support, process creation may be slow". This one means that Graphene-SGX cannot use OS mechanisms to fork a process and instead uses RPC to migrate state of the parent process to the child. Both `gcc` and `bash` programs that you test create new processes (fork); that's why you see these warnings. For more details, see the paper on Graphene-SGX at ATC'17. The relevant source code is `LibOS/shim/src/shim_checkpoint.c: do_migrate_process()`.

2. An error "file_map does not currently support writeable pass-through mappings on SGX". Graphene-SGX doesn't support memory-mapped files writable to the underlying OS file system. In other words, it is not possible in current Graphene-SGX to open a file using `mmap()` for writing *unless* you add a `MAP_PRIVATE` flag. So, to circumvent this problem, find the `mmap()` for all writable files in `gcc` code and add the flag. However, I do not know if this will break semantics of `gcc`. The relevant source code is `Pal/src/host/Linux-SGX/db_files.c: file_map()`.

So, you can safely ignore warning 1 but need some manual changes to `gcc` to fix error 2.

Hope this helps.

**Comment by donporter** [comment]
Thanks @dimakuv !  I will add on issue 1 that this warning should probably go away; on recent kernels, we have found that the graphene IPC module is no longer any faster than using the default OS pipe mechanism.   So 1 can be safely ignored.

2) GCC actually "works", but uses some unsupported file write modes.

I'm going to leave this issue open as feature requests.  I think it is probably time to just drop graphene IPC and warning 1, and, for someone who wants to get into coding on the project, issue 2 would not be a bad coding project.

**Comment by aua237032** [comment]
Thanks for the comments. I understood that warning 1 can be safely ignored, but when I run `./bash.manifest.sgx bash_test.sh`, warning 1 is displayed and the process freezes. Ctrl+C doesn't work, while freezing.  I would appreciate it if you could reply.

**Comment by donporter** [comment]
I suspect that these are independent issues.  I don't believe warning 1 has much to do with the hang or freeze.

Sometimes Ctrl+C does not work - this is a known issue.

**Comment by mkow** [comment]
Looks outdated, closing.
