### ISSUE TITLE
ImportError: cannot import name '_offsets'

### ISSUE THREAD

**Issue by triplewings** [oscarlab/graphene#2320]
### when I follow **Quick start with SGX support** and run step 5 sentence **make SGX=1**,  i receive error like this
~~~
Traceback (most recent call last):
  File "/home/leaf/graphene/python/graphenelibos/sgx_sign.py", line 19, in <module>
    from . import _offsets as offs # pylint: disable=import-error
ImportError: cannot import name '_offsets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leaf/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 17, in <module>
    from graphenelibos.sgx_sign import main
  File "/home/leaf/graphene/python/graphenelibos/sgx_sign.py", line 23, in <module>
    import generated_offsets as offs # pylint: disable=import-error
ModuleNotFoundError: No module named 'generated_offsets'
../../../../Scripts//../Pal/src/host/Linux-SGX/manifest.mk:26: recipe for target 'bootstrap_cpp.manifest.sgx.d' failed
make: *** [bootstrap_cpp.manifest.sgx.d] Error 1

~~~

I can make sure my SGX run successfully,  someone have met same problem?

# Thanks for any help plz~

**Comment by dimakuv** [comment]
The module `generated_offsets` is auto-generated by Graphene as part of the build process. Since Python complains that it cannot find this module, it means that Graphene build broke on something else and didn't auto-generate `generated_offsets`.

I think you have some other build error before this error. Please go through the build log and check what else breaks. Graphene must complain about something (e.g., some dependency is not installed on your machine).
