### ISSUE TITLE
Misinterpretation of ret return value on ra_tls_verify_common.c

### ISSUE THREAD

**Issue by srieyulianti** [oscarlab/graphene#2323]
Hi Graphene team,

I coincidentally find doubt in a function you wrote on ra_tls_verify_common. c library as the following:

`/*! compares if report_data from \quote corresponds to sha256 of public key in \p crt */
int cmp_crt_pk_against_quote_report_data(mbedtls_x509_crt* crt, sgx_quote_t* quote) {
    int ret;

    uint8_t sha[SHA256_DIGEST_SIZE];
    ret = sha256_over_crt_pk(crt, sha);
    if (ret < 0)
        return ret;

    ret = memcmp(quote->report_body.report_data.d, sha, SHA256_DIGEST_SIZE);
    if (ret)
        return MBEDTLS_ERR_X509_SIG_MISMATCH;

    return 0;
}`

On the line after memory comparation, do you mean if(ret<0) instead of if(ret)?

Thanks,
Sri

**Comment by dimakuv** [comment]
Everything looks correct to me. The return value of `memcmp()` is "unusual": https://man7.org/linux/man-pages/man3/memcmp.3.html#RETURN_VALUE. So `ret == 0` means "strings match" and `ret != 0` means "strings do not match".

**Comment by srieyulianti** [comment]
@dimakuv thank you. However, when I run the program, the result is inconsistent. Sometimes, I got the comparation pass but sometimes not.  Any idea what is the issue?

Thanks

**Comment by dimakuv** [comment]
It really depends on how you run the program, on which machines, etc. Without the additional description, it is impossible to know what exactly happens in your case.

Also, why do you think it fails in exactly this place in the code?

**Comment by srieyulianti** [comment]
Thanks for your response. Here some details relating to the platform:
CPU Info:
Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz

BIOS Info:
BIOS Information Vendor: Microsoft Corporation Version: Hyper-V UEFI Release v4.1 Release Date: 10/27/2020 ROM Size: 64 kB Characteristics: BIOS characteristics not supported ACPI is supported Targeted content distribution is supported UEFI is supported System is a virtual machine BIOS Revision: 4.1

Linux Firmware version:
linux-firmware/bionic-updates 1.173.20 all

OS Version:
NAME="Ubuntu" VERSION="18.04.5 LTS (Bionic Beaver)"

SGX SW Version:
intel_sgx: Intel SGX DCAP Driver v1.36.2 intel_sgx: Intel SGX Driver v2.11.0

I tried to modify your ra-tls-mbedtls example to make it suitable to run over the socket. When I run both client and server side at the beginning, I always got my certificate and quote comparison fail. However, when I changed the condition to be `ret<0`, then I got my comparison pass. But sometimes, it's not consistent too. My guess is because of the unstable communication over the socket.
I run server and client in different docker containers.

Thanks

**Comment by dimakuv** [comment]
> I tried to modify your ra-tls-mbedtls example to make it suitable to run over the socket. 

What does it mean, "to run over the socket"? That's what the example already does:
- The server program listens on port 4433 for TLS connections (https://github.com/oscarlab/graphene/blob/b9dbf7d7ff38534c85bb4510ea8e78b3a792346e/Examples/ra-tls-mbedtls/src/server.c#L182)
- The client program connects on port 4443 (https://github.com/oscarlab/graphene/blob/b9dbf7d7ff38534c85bb4510ea8e78b3a792346e/Examples/ra-tls-mbedtls/src/client.c#L301)

> However, when I changed the condition to be ret<0, then I got my comparison pass. But sometimes, it's not consistent too.

That's because you seem to compare garbage values. `<0` in memcmp case means "the first string is less than the second string". So if you compare garbage values, `<0` will succeed about 50% of the time.

I am sure the root cause is not in this memcmp. You must **not** modify this RA-TLS code. You should find the root cause in the way you create your enclaves and establish a connection. Right now I don't understand what exactly you're trying to achieve.
