### ISSUE TITLE
Problem reading protected files

### ISSUE THREAD

**Issue by daniel-weisse** [oscarlab/graphene#2359]
## Description of the problem
In reference to: https://github.com/oscarlab/graphene/pull/2194#issuecomment-834221612

I am using TensorFlow with Graphene + Marblerun. I would like to keep the pre-trained model encrypted at all times using keys provisioned by Marblerun. The model is ~105MB.

My current solution is encrypting the model first using a custom program and then decrypting it again using a premain function that saves the model to the protected file system. The key to decrypt / encrypt is set in the Marblerun manifest, to save to the protected file system I am using the applications seal key, also provided by Marblerun. (Since the seal key is kept secret i can not use it to encrypt the model in the first place)

## Steps to reproduce
Follow https://github.com/edgelesssys/graphene-tensorflow-demo but encrypt the model using pf_crypt and directly launch into TensorFlow, provide the key used by pf_crypt using the Marblerun manifest.

I have tested this running in docker and outside of docker.
`sgx.enclave_size` of 2G is sufficient to run TensorFlow with Graphene and Marblerun without model encryption.
I have unsuccessfully tested with enclave sizes of up to 8G.

## Expected results
Model is successfully read and available to TensorFlow

## Actual results
pf_open returns error -5

```bash
[P3536:T1:premain-graphene] debug: glibc register library /lib/x86_64-linux-gnu/libgcc_s.so.1 loaded at 0xcf10f000
[P3536:T1:premain-graphene] debug: glibc register library /lib/libc.so.6 loaded at 0xced0c000
2021-05-07 11:47:26.389513: I tensorflow_serving/model_servers/server.cc:89] Building single TensorFlow model file config:  model_name: resnet50 model_base_path: /models/resnet50-v15-fp32
2021-05-07 11:47:26.391498: I tensorflow_serving/model_servers/server_core.cc:465] Adding/updating models.
2021-05-07 11:47:26.391596: I tensorflow_serving/model_servers/server_core.cc:591]  (Re-)adding model: resnet50
debug: load_protected_file: models/resnet50-v15-fp32/1/saved_model.pb, fd 24, size 103714816, mode 1, create 0, pf 0xf08e6230
debug: load_protected_file: models/resnet50-v15-fp32/1/saved_model.pb, fd 24: opening new PF 0xf08e6230
error: pf_open(24, models/resnet50-v15-fp32/1/saved_model.pb) failed: -5
error: pf_file_attrquery: load_protected_file(models/resnet50-v15-fp32/1/saved_model.pb, 24) failed
2021-05-07 11:47:33.518446: I tensorflow_serving/core/basic_manager.cc:740] Successfully reserved resources to load servable {name: resnet50 version: 1}
2021-05-07 11:47:33.519616: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: resnet50 version: 1}
2021-05-07 11:47:33.519708: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: resnet50 version: 1}
debug: load_protected_file: models/resnet50-v15-fp32/1/saved_model.pb, fd 23, size 103714816, mode 1, create 0, pf 0xf08e6230
debug: load_protected_file: models/resnet50-v15-fp32/1/saved_model.pb, fd 23: opening new PF 0xf08e6230
error: pf_open(23, models/resnet50-v15-fp32/1/saved_model.pb) failed: -5
error: pf_file_attrquery: load_protected_file(models/resnet50-v15-fp32/1/saved_model.pb, 23) failed
```

## Additional information 
The examples using protected filesystem under `Examples/ra-tls-secret-prov` run fine.

I have also tested an example with Marblerun by modifying this helloworld example: https://github.com/edgelesssys/marblerun/tree/master/samples/graphene-hello

This sample also works without problems. It is able to read the protected file.

I modified the sample in the following way:
* Additions to `hello.c`
```C
// ---- 
  // Open file
  char *filename = "pf_test.txt";
  FILE *fptr;
  fptr = fopen(filename, "r");
  if (fptr == NULL) {
    printf("Cannot open file \n");
    exit(0);
  }
  // Read contents from file
  char c;
  c = fgetc(fptr);
  while (c != EOF) {
    printf ("%c", c);
    c = fgetc(fptr);
  }
  
  fclose(fptr);
  printf("\n");
  return 0;
}
```
* Additions to `hello.manifest.template`
```bash
sgx.protected_files.pf_test = "file:pf_test.txt"
```
* Additions to `manifest.json`
```json
"Files": {
  "/dev/attestation/protected_files_key": "00000000000000000000000000000000"
}
```

The test file is encrypted using `pf_crypt` and a 16 Byte key that is all 0.
Unlike the TensorFlow case this runs fine:
```bash
[P4247:T1:premain-graphene] debug: glibc register library /lib/libc.so.6 loaded at 0x4c8d2000
debug: load_protected_file: pf_test.txt, fd 16, size 4096, mode 1, create 0, pf 0x7b68d670
debug: load_protected_file: pf_test.txt, fd 16: opening new PF 0x7b68d670
debug: load_protected_file: pf_test.txt, fd 16, size 4096, mode 1, create 0, pf 0x7b68d670
debug: load_protected_file: pf_test.txt, fd 16: opening new PF 0x7b68d670
Hello world!

Commandline arguments:
Welcome!
Hello World from Marblerun!

Environment variables:
EDG_MARBLE_COORDINATOR_ADDR=localhost:2001
EDG_MARBLE_DNS_NAMES=localhost
EDG_MARBLE_TYPE=hello
EDG_MARBLE_UUID_FILE=uuid
LD_LIBRARY_PATH=/lib
MARBLE_PREDEFINED_INTERMEDIATE_CA=-----BEGIN CERTIFICATE-----
MARBLE_PREDEFINED_MARBLE_CERTIFICATE_CHAIN=-----BEGIN CERTIFICATE-----
MARBLE_PREDEFINED_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----
HELLO_WORLD=Hello World from Marblerun!
Hello from the protected file system
```

**Comment by dimakuv** [comment]
The Protected FS algorithm and format have a subtle requirement: the filepath used during initial encryption (via `pf_crypt`) **must be exactly the same** as when opening the protected file during enclave runtime.

From the enclave runtime logs, I see the path that Graphene uses: `models/resnet50-v15-fp32/1/saved_model.pb`.

Your initial encryption via `pf_crypt` should use the exact same path (it is relative, so the path should be relative). You specify the path in the `pf_crypt` command-line arguments. Could you please show how you perform encryption using `pf_crypt` -- the exact command line?

This requirement is rather obvious in hindsight -- Protected FS protects some metadata of the file (to protect against "swapped files" kinds of attacks). One of these metadata has to be the path of the file. Otherwise the attacker could abuse the fact that the application reads two files with the same name, but from different directories, and the attacker could swap these files, confusing the enclave application and leading to vulnerabilities.

So Protected FS has to store not just the base name of the file, but the whole path. And of course since the Graphene application may be deployed on different machines under different directories, Protected FS should use relative paths, not absolute paths.

If you want to delve into details, I recommend a couple things:
- Re-build whole Graphene in DEBUG mode (`make DEBUG=1`), and run with `loader.log_level = all`. This will enable `DEBUG_PF` macro and will output even more protected-fs info.
- Check the Protected FS format. Start here: https://www.tatetian.io/2017/01/15/understanding-sgx-protected-file-system/. Check our code, starting somewhere here: https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L267. Check the format: https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/protected-files/protected_files_format.h#L42
- Check the `pf_crypt` tool and its code: https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/tools/pf_crypt/pf_crypt.c#L113 and https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/tools/common/pf_util.c#L277

**Comment by dimakuv** [comment]
If this turns out to be your root cause, I would be happy to get your feedback on how to make this subtlety more prominent. Maybe a loud message during `pf_crypt`? Or a specific loud message during `pf_open()` that the file is probably not stored under the directory expected by the Protected FS?

Also, I see that you have an error `-5` which is `PF_STATUS_NO_MEMORY`. Which sounds wrong. Maybe it's just a small bug in Graphene.

**Comment by daniel-weisse** [comment]
It was indeed a problem caused by the filepath the model was saved to during encryption!

I used `pf_crypt` as follows:
```bash
pf_crypt --input models/resnet50-v15-fp32/1/saved_model.pb --output encrypted/saved_model.pb --wrap-key wrap_key
```
I fixed it by first copying `saved_model.pb` to a different folder and then running as follows:
```bash
pf_crypt --input plain/saved_model.pb --output models/resnet50-v15-fp32/1/saved_model.pb --wrap-key wrap_key
```
I think this is also similar to how it is used in the Graphene examples.

I then moved the file from `encrypted/` to a different folder which seems to have caused the problem.
Of course this problem did not pop up during my tests since i did not use folders in that case.

It probably makes the most sense to have a message in the descrption of `pf_crypt`. Maybe in the general description for the encryption mode or directly as a warning for the `--output` flag, notifying the user that the output path has to be the same as the path requested by the actual Graphene application.
Maybe an additional error message during `pf_open()` would also be helpful. I haven't looked to deep into the source code, but maybe it would be possible to show such a message only if the path stored in the metadata of the protected file does not match the actual file path?

Also regarding the `-5` error: This error seems to currently always pop up when something goes wrong with a protected file operation. It also happens when one provides the wrong decryption key.

**Comment by dimakuv** [comment]
@daniel-weisse Could you take a quick look at https://github.com/oscarlab/graphene/pull/2362? Feel free to leave your comments and suggest better wordings.

**Comment by dimakuv** [comment]
> Maybe an additional error message during pf_open() would also be helpful. I haven't looked to deep into the source code, but maybe it would be possible to show such a message only if the path stored in the metadata of the protected file does not match the actual file path?

I didn't implement this. First, we are not supposed to reveal the "expected" file path (embedded and encrypted in the protected-file metadata). Second, the message would be way to long. A shorter "Invalid header" is printed instead.
