### ISSUE TITLE
Implementing Intel MPK-related System Calls

### ISSUE THREAD

**Issue by vahldiek** [oscarlab/graphene#2396]
For one project we're interested to enable Intel MPK-related system calls (pkey_alloc, pkey_free, pkey_mprotect). Today they are not implemented. With this issue, I'd like to start a discussion about the correct way to implement them before actually starting to implement them.

`pkey_alloc` and `pkey_free` are specific function calls to create Intel MPK domains in the Linux kernel (it keeps track of which domains are active). `pkey_mprotect` is a variant of the regular `mprotect` system call with an additional parameter to assign a domain to the memory.

As a first step we would have to uncomment their implementations in `LibOS/shim/src/arch/x86_64/shim_table.c` and create the respective functions in the libOS to handle the system calls (e.g., in `graphene/LibOS/shim/src/sys/shim_mmap.c`).

At this point my understanding somewhat ends and I would like to ask for your guidance to pierce through the PAL layers and do the actual system calls. Any guidance is greatly appreciated.

**Comment by dimakuv** [comment]
1. How does an application running inside of Graphene use these syscalls?
2. How does Intel MPK work together with Intel SGX?
3. How is MPX + SGX bundle protected against a malicious OS doing weird things on `pkey_alloc`, `pkey_free`, etc.?
4. Do you want this to be transparent to the application (implemented in Graphene), or should Graphene forward requests from the app to the host?

For the actual implementation in Graphene, this is a good PR to follow: https://github.com/oscarlab/graphene/pull/1866. Basically, you need to create the emulation functions in the LibOS layer (as you already mentioned), define the PAL APIs, implement PAL wrappers somewhere in `Pal/src/`, and create implementations in each PAL (`Pal/src/host/Linux`, `Pal/src/host/Linux-SGX` and stubs in `Pal/src/host/Skeleton`).

But it would be very helpful to have a toy example of how the app uses Intel MPK syscalls, and how you want to port it to Graphene.

**Comment by vahldiek** [comment]
Thank you for the info and the pointer to the other PR.

1. I'm assuming that it uses the function calls defined in  `sys/mman.h` from libc. During the runtime of the application one or multiple pkeys would be allocated. After memory allocation the application would use pkey_mprotect to alter the memory protection key of a set of pages. Afterwards access to these pages is controlled via the WRPKRU instruction which allows to disable read and write permission on a pkey basis. If a key is no longer in use, the application may free a pkey.
2. Threat model wise it does not combine very well with SGX, since it is controlled by the OS and relies on a slightly modified threat model with weaker reliance where the will help the application in its execution.
3. To protect from weird things happening in pkey_alloc and pkey_free, Graphene will have to track the pkeys in use. This allows to check for double assignment of pkeys. But as mentioned in the previous section, the threat model is different as the PTEs are out of the control of SGX. There is no way to check for Graphene that the OS to actually set the pkey in the PTE via a pkey_mprotect call.
4. I believe there is no way to transparently implement this feature in Graphene alone, since Graphene does not have access to the PTEs and neither are they secure (OS could change them at any time). The aim should be to forward the application's request to the OS.

**Comment by MerveTurhan** [comment]
A toy example of Intel MPK: 

An MPK aware application runs within Graphene-SGX. For being able to protect some sensitive data (e.g. cryptographic keys, etc..) we would like to utilize Intel MPK e.g., via solutions like [libmpk](https://www.microsoft.com/en-us/research/uploads/prod/2019/05/park-libmpk.pdf). The sensitive data can be stored in a page is tagged with Intel MPK to protect it from third part library or other application code inside the enclave. 
The application first allocates a number of pkeys during initialization with **pkey_alloc()** and then tags certain pages with Intel MPK (**pkey_mprotect()**). We can change PKRU value at the runtime without doing syscall (execute WPKRU and RPKRU inside the enclave).   It means that page permissions can be changed at runtime.

**Comment by mkow** [comment]
To be honest I have troubles grasping the threat model here. If I understand correctly, this protects only from a very specific and limited attack scenario, which is:
* The attacker is network-based and does not collude with the enclave host.
* The attacker is exploiting a memory disclosure bug which allows leaking memory at arbitrary address, but not arbitrary code execution.
* The application inside Graphene itself implements MPK.

Note, that in this scenario, the same bug can be used successfully by the host, despite MPK - the host can just "disarm" MPK.

So, is this right, or am I missing something? If so, seems like a lot of work/complexity added to Graphene to mitigate quite specific types of attacks.

**Comment by vahldiek** [comment]
I agree with you Michal. MPK is a defense in-depth technology with weaker threat model than SGX. That doesn't mean it is useless or doesn't provide protections. I wouldn't call these attacks specific, since a lot of (today's) attacks are carried out this way. Handling this class of attacks and limiting their potential blast radius is beneficial to the eco-system.

For now the question was more about what would be good resources to start understanding a potential implementation and together come up with a plan to best implement such features.

**Comment by mkow** [comment]
> That doesn't mean it is useless or doesn't provide protections.

But also doesn't mean that it's a good idea to implement it.

> I wouldn't call these attacks specific, since a lot of (today's) attacks are carried out this way.

[citation needed] :)
Remember that this isn't protecting against generic memory disclosures, but against a very specific scenario.

This may be an interesting research project, but if you want this to be included in something intended for production, then you need to justify it. Not all mitigations are worth adding, all of them introduce additional complexity which may itself cause security bugs and make the project harder to maintain. Extreme example: we could make our sources unreadable by obfuscating variable names, which would definitely make attackers lives harder, but same as ours.
I think a good example of such a failed mitigation is XSS protector, which was a "defense in-depth" trying to just "make attacks harder", which turned out to sometimes introduce security bugs to websites which would be perfectly secure without it, so it was later reverted.

**Comment by dimakuv** [comment]
@mkow Let people do their research PoC :)

> For now the question was more about what would be good resources to start understanding a potential implementation and together come up with a plan to best implement such features.

Is  #1866 sufficient for your purposes for now, or do you have more questions on how this stuff is implemented in Graphene?

**Comment by mkow** [comment]
> @mkow Let people do their research PoC :)

As I said, for research it's fine, but I'm skeptical about having this in the mainline Graphene :)

Anyways, I'm not actually sure if this issue was about adding this to Graphene (that was my impression) or maybe that you want to implement this yourself only as an experiment, currently without plans for merging?

**Comment by MerveTurhan** [comment]
I got inspiration from [Enclavedom.](https://arxiv.org/pdf/1907.13245.pdf). It is about privileged separation on Graphene using Intel-MPK.   Good to check.  Also, I have checked adding a [new system call tutorial on Graphene](https://graphene.readthedocs.io/en/latest/devel/new-syscall.html). But I was a bit lost in that tutorial.  I couldn't add intel_mpk related system call to Graphene, probably because of my lack of experience.   My request was an expanded version of this tutorial.

As you know that we can use edge8rtool to generate code automatically for the intel-sgx native applications.  I thought that adding or calling a new system call for graphene must easier than intel-sgx native application.  

Thanks for the suggestion. Let me check #1866

**Comment by boryspoplawski** [comment]
Personal option ahead: I've skimmed through the paper you linked and I have to say I'm not impressed:
- example quote that's not true: `At every ecall and ocall, Intel SGX encrypts or decrypts any memory contents being passed  between the  context.`,
- they keep using "untrusted third-party library" while also admitting that such code runs inside the enclave and hence must be generally trusted,
- authros claim that `As in TEEs, EnclaveDom does not trust any hardware out-side  the  CPU,  system  software  including the OS and any hypervisor, other applications running on the same machine alongside the TEE application, as well as the untrusted component of the application running outside the enclave.` yet they also allow for initialization routines  happening in untrusted code. Also, to the best of my knowledge, MPK operates on the level of Page Tables and as such must be set up by host-OS - the very same we do not trust. This seems to be a major contradiction. 
- Case study/Analysis - I don't think these require comments:
  - "In this case study, the adversarial application **imports** our specially crafted **malicious library** which attempts to **corrupt Graphene-SGX’s file descriptor table** (or FD table).` 
  - "**Untrusted in-enclave code** may attempt to manipulate the value of the PKRU by **including direct WRPKRU instructions** within its code."

As for general discussion in this thread: I don't think adding something like that to "mainline" Graphene will be of any use (mainly due to requirement of trusting the host-OS).

>  I thought that adding or calling a new system call for graphene must easier than intel-sgx native application.

It won't be easier: afaik the `edger8r`  tool merely creates stub code to **passthrough** a syscall to the host-OS. In Graphene we provide complete emulation inside enclave where possible, only calling host-OS syscalls where absolutely necessary (and that also goes via PAL layer).

**Comment by MerveTurhan** [comment]
Concerning the need to trust the OS in enclavedom: note that the initial page table configuration for an enclave is not trusted but validated during the attestation process and protected by the EPCM/TLB check mechanism at runtime. That should include the protection keys as they are encoded in the virtual addresses. 

As a side note, [Intel Software Developer Manual ](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-vol-3d-part-4-manual.pdf) has an INTEL SGX INTERACTION WITH PROTECTION KEYS section.  Please check 42.17. I thought that the Intel community are planning to do something about this issue.  

Talking about the PAL layer, is there any documentation of the PAL implementation/architecture available? Just looking at the code, it is really hard to understand the inner workings of e.g. the memory management in Graphene.

**Comment by dimakuv** [comment]
> Talking about the PAL layer, is there any documentation of the PAL implementation/architecture available? Just looking at the code, it is really hard to understand the inner workings of e.g. the memory management in Graphene.

Sorry, I'm afraid there is no documentation. The internal implementation of (the current state of) Graphene is not described anywhere. We haven't had the time/energy/resources for this.

However, I think the FOSDEM talk summarizes some of the implementation details: https://fosdem.org/2021/schedule/event/tee_graphene/.

If you have any specific questions about LibOS/PAL code, you can ask here.

**Comment by boryspoplawski** [comment]
> Concerning the need to trust the OS in enclavedom: note that the initial page table configuration for an enclave is not trusted but validated during the attestation process and protected by the EPCM/TLB check mechanism at runtime. That should include the protection keys as they are encoded in the virtual addresses.

Page table is not validated, you only validate tuples of `(address, size, type+permissions)` and memory contents and afaik protection keys are no included in any of those. Besides, I'm pretty sure there is no place to store them in SGX structures (including EPCM), so the CPU cannot verify them (outside of normal PT walk, but that is provided by untrusted host).

**Comment by mkow** [comment]
Ok, seems we don't plan to have this feature in mainline Graphene (if you think otherwise, then please convince us that it makes sense), so I'm closing this issue, as we use issues as a project-wise TODO-list. Feel free to continue discussion here though.
