### ISSUE TITLE
GCC Example failed with RHEL 8 & CentOS 8.2

### ISSUE THREAD

**Issue by anjalirx-intel** [oscarlab/graphene#2489]
## Description of the problem
**CentOS:**
GCC Example failed with "collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped"

**RHEL**
Graphene-Direct: 
Inconsistency detected by ld.so: dl-call-libc-early-init.c: 37: _dl_call_libc_early_init: Assertion `sym != NULL' failed!
Graphene-SGX:
gcc: error trying to exec '/usr/libexec/gcc/x86_64-redhat-linux/8/cc1': execv: Permission denied

## Steps to reproduce
**For Graphene-Direct**
```
cd Examples/gcc
make -j8 all
make check
```

**For Graphene-SGX**
Need to add these 2 lines in manifest.template for SGX
```
sgx.allowed_files.cc1 = "file:/usr/libexec/gcc/x86_64-redhat-linux/8/cc1"
sgx.allowed_files.collect2 = "file:/usr/libexec/gcc/x86_64-redhat-linux/8/collect2"
```

```
make -j8 SGX=1 all
make SGX=1 check
```

## Expected results
```
make SGX=1 check
Compiling hello.c...
graphene-sgx gcc test_files/helloworld.c -o test_files/hello
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
./test_files/hello
Hello world (./test_files/hello)!
rm -f test_files/hello


Compiling bzip2.c...
graphene-sgx gcc test_files/bzip2.c -o test_files/bzip2
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
rm -f bzip2.tmp
./test_files/bzip2 -z test_files/bzip2.copy
./test_files/bzip2 -d test_files/bzip2.copy.bz2
diff -q test_files/bzip2 test_files/bzip2.copy
rm -f test_files/bzip2 test_file/bzip2.copy


Compiling gzip.c...
graphene-sgx gcc test_files/gzip.c -o test_files/gzip
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
./test_files/gzip test_files/gzip.copy
./test_files/gzip -d test_files/gzip.copy.gz
diff -q test_files/gzip test_files/gzip.copy
rm -f test_files/gzip test_files/gzip.copy
```

## Actual results
**CentOS**
```
[intel1@localhost gcc]$ sudo make check
\n\nCompiling hello.c...
graphene-direct gcc test_files/helloworld.c -o test_files/hello
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
make: *** [Makefile:76: check] Error 1

```

```
[intel1@localhost gcc]$ make SGX=1 check
\n\nCompiling hello.c...
graphene-sgx gcc test_files/helloworld.c -o test_files/hello
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
make: *** [Makefile:76: check] Error 1
```

**RHEL:**
[intel@intel gcc]$ make check
```
\n\nCompiling hello.c...
graphene-direct gcc test_files/helloworld.c -o test_files/hello
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
Inconsistency detected by ld.so: dl-call-libc-early-init.c: 37: _dl_call_libc_early_init: Assertion `sym != NULL' failed!
collect2: error: ld returned 127 exit status
make: *** [Makefile:76: check] Error 1
```

[intel@intel gcc]$ make SGX=1 check
```
\n\nCompiling hello.c...
graphene-sgx gcc test_files/helloworld.c -o test_files/hello
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
gcc: error trying to exec '/usr/libexec/gcc/x86_64-redhat-linux/8/cc1': execv: Permission denied
make: *** [Makefile:76: check] Error 1
[intel@intel gcc]$
```

[centos_gcc_trace.log](https://github.com/oscarlab/graphene/files/6742085/centos_gcc_trace.log)

**Comment by mkow** [comment]
Please use proper Markdown in your issues, they are unreadable.
Also, could you run this with debug output and with Graphene compiled in debug mode, and then check if there are any interesting lines in the output?

**Comment by dimakuv** [comment]
GCC works for me on Ubuntu 18.04.

Looks like you test GCC on some RedHat distro? It seems to have quite different paths for GCC components and probably a quite different GCC version itself... Unfortunately, I don't see how to reproduce this failure on our developers' Ubuntus.

**Comment by anjalirx-intel** [comment]
@mkow I hope its fine too read now.  I have attached the trace logs for it.

@dimakuv Yes, it is tested on CentOS 8.2 and gcc version is different. 

```
[intel1@localhost gcc]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)
```

**Comment by dimakuv** [comment]
Ok, I debugged this. The root cause is really convoluted.

The actual failing executable is `/usr/bin/ld`. On CentOS, it is backed by `/usr/bin/ld.bfd` actual executable:
```
$ ll /usr/bin/ld
lrwxrwxrwx. 1 root root 20 Jun 22 12:26 /usr/bin/ld -> /etc/alternatives/ld
$ ll /etc/alternatives/ld
lrwxrwxrwx. 1 root root 15 Jun 22 12:26 /etc/alternatives/ld -> /usr/bin/ld.bfd
```

This `/usr/bin/ld.bfd` is very peculiar in the path where it searches for Glibc:
```
[P722412:T33:ld] trace: ---- shim_openat(AT_FDCWD, "/usr/lib64/libc.so.6", O_RDONLY|0x80000, 0000) = 0x3
```

As you can see, Glibc is loaded from the host directory `/usr/lib64/` -- which is *not* the Graphene-specific `/lib` directory. In other words, Graphene loads the host Glibc and not Graphene-patched Glibc. The Glibc on CentOS 8.2 also has a quite different version from Graphene-patched one:
```
$ /usr/lib64/libc.so.6
GNU C Library (GNU libc) stable release version 2.28.
```

So Graphene loads and executes the wrong-version unpatched Glibc, at which point all bets are off. This wrong Glibc expects something from `arch_prctl()` syscall, and fails when Graphene emulates it in a slightly unexpected to Glibc way. (Actually, here I got stuck in my debug because Glibc is unreadable; also this fault happens very deep in GCC execution, in the third child `collect2` which also execves into `ld`, so debugging is a nightmare).

**Comment by dimakuv** [comment]
I tried to trick this `/usr/bin/ld.bfd` executable by specifying this in the manifest:
```
fs.mount.lib123.type = "chroot"
fs.mount.lib123.path = "/usr/lib64"
fs.mount.lib123.uri = "file:/blabla/graphene/built/lib64/graphene/runtime/glibc"
```

This forced `/usr/bin/ld.bfd` executable to pick up our Graphene-patched Glibc, and the workload continued past the previous segfault point. However, this executable got stuck a bit later when it tried to open `crti.o` (which is the Graphene version, not the host version as should be):
```
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crti.o: unable to initialize decompress status for section .
debug_aranges
```

So basically this `/usr/bin/ld.bfd` executable searches in `/usr/lib64` for both Glibc libraries but also for other libraries/object files. The Glibc libraries must come from Graphene, but other libraries must come from the host. Graphene cannot shadow different parts of the same path to different host paths, so this is not fixable.

Just for completeness, on Ubuntu 18.04 the ld executable is different:
```
$ ll -h /usr/bin/ld
lrwxrwxrwx 1 root root 19 Feb 12 00:45 /usr/bin/ld -> x86_64-linux-gnu-ld*
$ ll /usr/bin/x86_64-linux-gnu-ld
lrwxrwxrwx 1 root root 23 Feb 12 00:45 /usr/bin/x86_64-linux-gnu-ld -> x86_64-linux-gnu-ld.bfd*
```

So on Ubuntu, we end up in the `x86_64-linux-gnu-ld.bfd` executable which searches for Glibc under `/lib` (exactly as expected). That's why GCC example works on Ubuntu.

**Comment by anjalirx-intel** [comment]
Updated the issue for RHEL as well.
