### ISSUE TITLE
pread fails when file descriptor refers to a directory

### ISSUE THREAD

**Issue by anjalirai-intel** [oscarlab/graphene#2539]
## Description of the problem
pread() should return -1 and errno should be EISDIR.

## Steps to reproduce
Run LTP Test pread03

## Expected results
pread03     1  TPASS  :  pread() fails with expected error EISDIR errno:21

## Actual results
pread03    1 TFAIL : pread() fails, EISDIR, unexpected errno:13, expected:21

## Label
P0, bug

**Comment by dimakuv** [comment]
We had a clush of two PRs fixing this issue: #2577 from @sahason and #2626 from @pwmarcz.

Sorry for this. I guess the reason why this happened was because we didn't have the Assignee in this issue :( So @pwmarcz didn't notice that this was already taken by @sahason. We need to be more careful with assignments.

Since #2626 is a more "complete" PR, let's merge it instead of #2577.
