### ISSUE TITLE
Graphene and Ocaml

### ISSUE THREAD

**Issue by ivanatodvuk** [oscarlab/graphene#254]
Hi,

I managed to run a simple C programs which calls some OCaml functions by
changing the Makefile in graphene/Libos/shim/test/native (please see the
attached native.zip). This way, I get the executable, which is then
called by PAL and executed by Graphene (please correct me if I am wrong).

Although the code runs correctly, I am wondering is it possible to call
the same enclave code multiple times without closing the enclave after
each call?  For example, we need an application that will be able to
make several calls of the enclave functions (please see the attached
hello-enclave-all-in-C.tar.gz)?  The issue with the current approach (in
native.zip) is that it creates an executable, instead of an .so file.

Moreover, I read at several places in Graphene-SGX paper that Graphene-SGX enables dynamic
loading, but I would be very grateful if you could show me some examples.

Thank you!

[hello-enclave-all-in-C.tar.gz](https://github.com/oscarlab/graphene/files/2482387/hello-enclave-all-in-C.tar.gz)
[native.zip](https://github.com/oscarlab/graphene/files/2482388/native.zip)

**Comment by dimakuv** [comment]
> I managed to run a simple C programs which calls some OCaml functions by
> changing the Makefile in graphene/Libos/shim/test/native (please see the
> attached native.zip). This way, I get the executable, which is then
> called by PAL and executed by Graphene (please correct me if I am wrong).

Technically, it is executed by Graphene using a Linux-SGX PAL. The terminology is not important for your questions though.

> Although the code runs correctly, I am wondering is it possible to call
> the same enclave code multiple times without closing the enclave after
> each call? For example, we need an application that will be able to
> make several calls of the enclave functions (please see the attached
> hello-enclave-all-in-C.tar.gz)? The issue with the current approach (in
> native.zip) is that it creates an executable, instead of an .so file.

Your problem is interesting. The way I understand it, you cannot use Intel SGX SDK because it doesn't support OCaml runtime. On the other hand, Graphene-SGX runs OCaml code but lacks the flexibility of SGX SDK.

Graphene-SGX's main goal is to seamlessly run *whole unmodified applications* inside an SGX enclave. In your case, you want to *split* the application into untrusted host and trusted enclave functionality. Therefore, your use-case doesn't align with Graphene-SGX's philosophy well.

However, there are ways to "hack" Graphene-SGX for your use-case:

1. If most of the time you will spend in the SGX enclave, and you need to perform untrusted application logic only infrequently, then you can hi-jack any of the system calls provided by Graphene-SGX and replace their usual logic with your application's logic. E.g., you can replace logic in `sgx_ocall_sleep()` with your app's logic; when this application finishes, your enclave will continue running; by passing data in the `pms` argument, you can control what the enclave and app need to do. You also need to be sure that OCaml runtime itself doesn't use `sleep()` syscall.

2. If most of the time is spent in the application, and enclave logic is executed only infrequently, then it is better to split your untrusted app and enclave into two processes and let them communicate via Unix pipes or TCP/IP network. You will have to re-write your enclave logic in a simple web-server and listen for your untrusted app's connection. The untrusted app will send packets to the enclave every time it needs to execute enclave's OCaml functions.

Notice that (1) is ugly and plain wrong but can be prototyped fast and must have generally good performance; (2) requires more work but is flexible -- basically your OCaml logic is encapsulated in a stand-alone service and any application can invoke it.

If you provide more info on what exactly you want to do, we may come up with something better.

> Moreover, I read at several places in Graphene-SGX paper that Graphene-SGX enables dynamic
> loading, but I would be very grateful if you could show me some examples.

If you mean "dynamically loaded shared libraries", then it is straight-forward, check the [Manifest of Lighttpd]https://github.com/oscarlab/graphene/blob/master/LibOS/shim/test/apps/lighttpd/lighttpd.manifest.template) for example. The Lighttpd executable requires `libssl` and `libcrypto` libraries to run, Graphene-SGX's internal dynamic loader will automatically recognize these dependencies and will try to load them. In the Manifest, you just need to specify where to find the libraries.

If you mean "dynamic linking", Graphene-SGX also supports this. You need to add `libdl` (dynamic linker) library to the Manifest; see Lighttpd Manifest example. Then your enclave can perform the usual `dlopen()`, `dlsym()`, etc.

If you have more questions, feel free to ask.

> [hello-enclave-all-in-C.tar.gz](https://github.com/oscarlab/graphene/files/2482387/hello-enclave-all-in-C.tar.gz)
> [native.zip](https://github.com/oscarlab/graphene/files/2482388/native.zip)

Please do not attach archives. It is better to create a Github repository or a gist and point people to it.

**Comment by mkow** [comment]
Closing.
@ivanatodvuk: Feel free to reopen if you have more questions regarding this topic.
