### ISSUE TITLE
Expose quote outside of enclave

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#2619]
## Description of the problem
As the document mentioned in https://graphene.readthedocs.io/en/latest/attestation.html?highlight=%2Fdev%2Fattest
`Remote Attestation is exposed to the application via /dev/attestation pseudo-filesystem. Remote attestation in Graphene uses the Intel SGX PSW’s AESM service and the Intel DCAP libraries under the hood.
Secure Channel is constructed using the RA-TLS libraries. RA-TLS uses raw /dev/attestation pseudo-files under the hood.`

Therefore, the pseudo file /dev/attestation only accessible inside of enclave, but usually the unmodified application isn't aware of that quote file exist. However, it is more valuable to let external application to access the quote file in outside of enclave to assist the customized attestation process.

We suggest the quote to be written into the following location in system, thanks.
`/var/run/[Graphene|Gramine]/sgx_quote.<PID>.<MRenclave>

**Comment by dimakuv** [comment]
What is the use case for dumping the SGX quote in some location on the host system?

I'm not against the idea (in fact, this will probably be needed for services like Microsoft Azure Attestation), but what is the exact scenario here?

Note that `/dev/attestation/` pseudo-files are exposed to the application, but the application itself typically doesn't use these files -- instead the helper libraries like RA-TLS and Secret Provisioning use these interfaces.

**Comment by mkow** [comment]
We can't generate it without cooperation from the application, someone has to fill the user data field. Why would you need a quote without any data there?

**Comment by bigdata-memory** [comment]
The things to fill the field of user data could be any that specified in manifest file. e.g. wrapped keys, fingerprints, access token. thanks.

**Comment by mkow** [comment]
> The things to fill the field of user data could be any that specified in manifest file. e.g.
> wrapped keys

If you mean protected files wrap key, then no, it can't be specified there in production configurations, because manifest is known to the untrusted host.

> fingerprints

You can't exchange any secrets with an enclave if user data field in quote contains just some unique id. How would you start e.g. an in-enclave-terminated TLS this way? Or any other secure channel?

> access token

Ditto, manifest is known to the host, you can't put secrets there.

> thanks.

Thanks.

**Comment by bigdata-memory** [comment]
We definitely don't suggest our customers to attach sensitive info in quote. but it is quite flexible to allow user to configure it according to their own usages, in some cases, user just needs to assure those data are sourced from enclave in question, e.g. application output results, the secret fingerprints, the encrypted keys to exchange information, even the protected access token to grant external system read permission temporarily.

**Comment by mkow** [comment]
> We definitely don't suggest our customers to attach sensitive info in quote

You suggested exactly this in your previous response. Citing: "The things to fill the field of user data could be [..] e.g. [...], access token".

> but it is quite flexible to allow user to configure it according to their own usages

It already is, the app may write anything it wants through our `/dev/attestation/user_report_data` interface. See https://graphene.readthedocs.io/en/latest/attestation.html.

> in some cases, user just needs to assure those data are sourced from enclave in question, e.g. application output results, the secret fingerprints, the encrypted keys to exchange information, even the protected access token to grant external system read permission temporarily.

a) It's already possible.
b) Your proposed solution doesn't allow for this, because you would need to specify this in a public manifest.

Summarizing: I don't see any legitimate use for such a feature, so I'm closing it until someone provides a legitimate use case.
