### ISSUE TITLE
Issue with libprotobuf version.

### ISSUE THREAD

**Issue by kvijay1918** [oscarlab/graphene#2697]
I am using Ubuntu v21.10 and kernel 5.13 and the code name is impish.

root@a4bf01694f20:# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 21.10
Release: 21.10
Codename: impish
root@a4bf01694f20:#

root@a4bf01694f20:~# uname -r
5.13.0-20-generic

root@a4bf01694f20:~/vj-scripts# uname -m
x86_64

I tried installing psw installer. Got the below error.

The following packages have unmet dependencies:
libsgx-epid : Depends: libprotobuf17 but it is not installable
Recommends: libsgx-aesm-epid-plugin (>= 2.15.100.3-focal1) but it is not going to be installed
libsgx-launch : Depends: libprotobuf17 but it is not installable
Recommends: libsgx-aesm-launch-plugin (>= 2.15.100.3-focal1) but it is not going to be installed
libsgx-uae-service : Depends: libsgx-quote-ex (>= 2.15.100.3-focal1) but it is not installable
E: Unable to correct problems, you have held broken packages.

Further I analyzed the error. I came to know that, libprotobuf17 is supported only on Ubuntu v20.04 and for the code name focal.

Is it possible to install libprotobuf17 on Ubuntu v21.10 with code name impish ? Since it supports only libprotobuf23.

Thanks,
Vijay.

**Comment by kvijay1918** [comment]
I am using Ubuntu v21.10 and kernel 5.13 and the code name is impish.

root@a4bf01694f20:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish
root@a4bf01694f20:~#

root@a4bf01694f20:~# uname -r
5.13.0-20-generic

root@a4bf01694f20:~/vj-scripts# uname -m
x86_64

I tried installing psw installer. Got the below error.

The following packages have unmet dependencies:
libsgx-epid : Depends: libprotobuf17 but it is not installable
Recommends: libsgx-aesm-epid-plugin (>= 2.15.100.3-focal1) but it is not going to be installed
libsgx-launch : Depends: libprotobuf17 but it is not installable
Recommends: libsgx-aesm-launch-plugin (>= 2.15.100.3-focal1) but it is not going to be installed
libsgx-uae-service : Depends: libsgx-quote-ex (>= 2.15.100.3-focal1) but it is not installable
E: Unable to correct problems, you have held broken packages.

*********************************************************

Further I analyzed the error. I came to know that, libprotobuf17 is supported only on Ubuntu v20.04 and for the code name focal.

Is it possible to install libprotobuf17 on Ubuntu v21.10 with code name impish ? Since it supports only libprotobuf23.

Thanks,
Vijay.

**Comment by dimakuv** [comment]
Dear Vijay,

Please post this issue in the official Intel SGX SDK & PSW repository: https://github.com/intel/linux-sgx

You found an interesting issue. I believe you're correct, there is a mismatch in what your Ubuntu 21.10 provides and what the SGX PSW package expects. Hopefully the Intel SGX SDK & PSW people can help you.

In the meantime, I can only recommend to downgrade your machine to a more "tested" Ubuntu 20.04 version. This version for sure works correctly with both Intel SGX SDK & PSW and Gramine.

I'll close your issue here since it's not related to Gramine itself (also note that "Graphene" changed its name to "Gramine" and moved to a new repository: https://github.com/gramineproject/gramine).
