### ISSUE TITLE
Potential out-of-bounds access in shim_do_epoll_wait()

### ISSUE THREAD

**Issue by thomasknauth** [oscarlab/graphene#277]
Since j could potentially be 2, [this](
https://github.com/oscarlab/graphene/blob/f07dfd052f476912617de74a0835f83d63f309eb/Pal/src/host/Linux-SGX/db_object.c#L170) appears to be a potential out-of-bounds access. Now, I don't know if some magic un[der]documented invariant actually prevents this from ever happening.

**Comment by donporter** [comment]
Ack.  I'm not sure myself.  I agree that some documentation (or an assertion) here would not be amiss.

**Comment by chiache** [comment]
Hi, Thanks for reporting this issue. I took a close look at this implementation again. Although this part does not necessarily contain any bug right now, I agree that it is a poor design and can potentially introduce bugs in the future.

You see, the size 2 in the definition of `struct pal_handle` ([here](https://github.com/oscarlab/graphene/blob/f07dfd052f476912617de74a0835f83d63f309eb/Pal/src/host/Linux-SGX/pal_host.h#L91)) actually doesn't matter. The actual number of file descriptors in each PAL handle pretty much depends on the handle type. For example, a __file__ handle contains exactly one file descriptor and a __pipeprv__ handle contains exactly two file descriptors. As the code [here](https://github.com/oscarlab/graphene/blob/f07dfd052f476912617de74a0835f83d63f309eb/Pal/src/host/Linux-SGX/db_object.c#L160) shows, the only way of telling the number of pointers in an opaque pointer is by consulting the `flags`. The rules are basically as follows:

- If the Nth bit (N is 1~3) of `flags` is set, then the Nth elements of `fds` is a valid, readable integer.
- If the (3 + N)th bit (N is 1~3) of `flags` is et, then the Nth elements of `fds` is a valid, writable integer.

Based on this logic, if the 1th and 4th bits of `flags` is set, and no other bits are set, then the handle has exactly one file descriptor that is readable and writable.

Another example: if the 1th and 5th bits of `flags` is set, and no other bits are set, then the handle contains two file descriptors, the first one is readable and the second one is writable.

As demonstrated, this scheme is space-efficient but prone to mistakes. One obvious problem is that the correctness of this code largely depends on assigning the right value to `flags`. Since the handles are initialized all over the place, we can't guarantee that the invariant will be always followed in the future. 

I would certainly prefer rewriting this design in the near future.

**Comment by thomasknauth** [comment]
I guess the MAX_FDS constant puts a limit on the potential read/write encodings in the bit mask then, since none of the potential pal_handles has three FDs as far as I can tell. Still seems a bit dodgy.

**Comment by dimakuv** [comment]
This was fixed during rewrite of the poll logic. Closing.
