### ISSUE TITLE
Internal memory fault at 0x0 when using SGX + xgboost library

### ISSUE THREAD

**Issue by Bizyroth** [oscarlab/graphene#308]
Hello

I'm using graphene to run python program and especially python programs using the xgboost library.

When i'm trying to run a program containing `import xgboost` (even an Hello World), i've go an error:
`Internal memory fault at 0x0 (IP = +0xa1a9f, VMID = 1812475901, TID = 1)`

I try to increase the size of the enclave, the size of the stack, the maximum number of thread and the size of break limit but it doesnt change anything.

### Identification of the problem.
1) The first time i ran the program, i made a whole import of all the library of python (2.7 by the way).
I had the `Internal memory fault at 0x0 (IP = +0xa1a9f, VMID = 1812475901, TID = 1)` but i thought it was due to the size of all the python library.

2) Then i tried to import just the library needed. I had then one by one until i have to add the `libgfortran-ed201abd.so.3.0.0`. 

It must be a compatibility problem because the libgfortran is small (3KB).
Here is the manifest and 3 debug files:
* out_before_adding_libgfortran: logs before adding the libgfortran in the trusted files
* out_debug: logs with debug option
* out_with_bug: logs without debug option

[out_before_adding_libgfortran.txt](https://github.com/oscarlab/graphene/files/2615200/out_before_adding_libgfortran.txt)
[out_debug.txt](https://github.com/oscarlab/graphene/files/2615201/out_debug.txt)
[out_with_bug.txt](https://github.com/oscarlab/graphene/files/2615202/out_with_bug.txt)

[python.manifest.template.txt](https://github.com/oscarlab/graphene/files/2615206/python.manifest.template.txt)

The program is used is only:
`import xgboost`
`print("Hello world")`

If you want that i make more test ask me.

**Comment by donporter** [comment]
Hmm...  This does seem like a legit bug.  

These lines in the debug output jump out at me: 

[     1] ---- shim_openat(AT_FDCWD,"/sys/devices/system/cpu",O_RDONLY|2204000,0000) = -2
[     1] handle signal (counter = 0)
[     1] ---- shim_time(0x0) = 1543232448
[     1] handle signal (counter = 0)
[     1] ---- shim_open("/sys/devices/system/cpu/online",O_RDONLY|2000000,200000) ...
[     1] ---- return from shim_open(...) = -2
[     1] handle signal (counter = 0)
[     1] ---- shim_open("/proc/stat",O_RDONLY|2000000,200000) ...
[     1] ---- return from shim_open(...) = -2
[     1] handle signal (counter = 0)
[     1] ---- shim_open("/proc/cpuinfo",O_RDONLY|2000000,200000) ...
[     1] bkeep_unmapped: 0x3924c000-0x39251000 => slab
[     1] bkeep_unmapped: 0x3ba03000-0x3ba04000 => slab
[     1] ---- return from shim_open(...) = 11
[     1] handle signal (counter = 0)
[     1] ---- shim_read(11,0x26aa5430,8192) ...
[     1] ---- return from shim_read(...) = 1632

I wonder if the culprit is one of these sys or proc files not having what this library is looking for.

I would be curious if you can send us the output of 'addr2line' with this faulting IP.

**Comment by Bizyroth** [comment]
> I would be curious if you can send us the output of 'addr2line' with this faulting IP.

The `pal_loader` is not recognized by addr2line.

I've got the same problem when i try `addr2line -e ./python.manifest.sgx scripts/test.py 0xa1a9f`

**Comment by donporter** [comment]
Is this on SGX or normal Linux?

Try addr2line on Runtime/libsysdb.so, or possibly Runtime/pal-Linux{-SGX}.so

**Comment by Bizyroth** [comment]
Hi
After doing multiple aad2line to the different library, i've got a result on the libc.so:
```addr2line -o Runtime/libc.so 0xa1a9f```
The result is:
```/graphene/LibOS/glibc-2.19/wcsmbs/../stdlib/strtod_l.c:930```

I'm using graphene on SGX by the way

**Comment by donporter** [comment]
Sounds like a legit bug.  I'm wondering if we have an error in our /proc/cpuinfo implementation that is giving back some unexpected values.

**Comment by Bizyroth** [comment]
Do you have an idea of how you can fix that bug?

**Comment by donporter** [comment]
I'm not sure.  I'll take a look when I get a chance, but it won't be immediately.

If you are interested, just cat the contents of /proc/cpuinfo on graphene SGX and on your native system, and post the results.  Maybe a difference will jump out.

**Comment by liaoyupeng** [comment]
This is what I got.

Traceback (most recent call last):
  File "scripts/1.py", line 7, in <module>
    print(open('/proc/cpuinfo').read())
IOError: [Errno 21] Is a directory: '/proc/cpuinfo'
DkProcessExit: Returning exit code 1

So looks like /proc/cpuinfo is a directory instead of a file?

**Comment by liaoyupeng** [comment]
@Bizyroth btw how did you get the debug output? I tried fixing the /proc/cpuinfo issue but for some reason it still fails so would like to report it.

**Comment by mkow** [comment]
@liaoyupeng You need to add `loader.debug_type = inline` to your manifest.

**Comment by donporter** [comment]
This looks like an easy enough bug to fix.  This line is wrong:

https://github.com/oscarlab/graphene/blob/00c4ed02537868def1ea1b545413d04d75a855a2/LibOS/shim/src/fs/proc/info.c#L30

It should be S_IFDIR.  I'll open a PR to change this.

**Comment by mkow** [comment]
Seems outdated, closing. The line quoted by Don is different right now: https://github.com/oscarlab/graphene/blob/3908b904741f606dc436a1fd28d849863f408bd3/LibOS/shim/src/fs/proc/info.c#L24
