### ISSUE TITLE
The files in the '/proc' directory are empty

### ISSUE THREAD

**Issue by njuyuanrui** [oscarlab/graphene#36]
I've mounted the ‘/proc’ to the file ‘/proc’ and then I try to read the '/proc/stat' file but cannot read anything。
It actually found the file without throwing the "No such file" exception, just read nothing.
How can I find the files in '/proc' directory?

**Comment by chiache** [comment]
Do you mean mounting the host proc file system to /proc in the library OS? I will strongly suggest not to do so. The proc file system is a pseudo file system which should reflect the OS states. The library OS has its own OS states so should only run its own proc file system.

**Comment by njuyuanrui** [comment]
But how to read the proc files of the library OS?  There are no proc files in libOS if I don't mount th proc files of host system.

**Comment by chiache** [comment]
There is a simple proc file system in Graphene.
```
Graphene/LibOS/shim/test/native$ ./pal ls.manifest /proc
1
cpuinfo
meminfo
self
```

If you need a specific file in proc but Graphene hasn't implement it yet, you can try to mount only that file into graphene. Like this:
```
fs.mount.bin.type = chroot
fs.mount.bin.path = /proc/stat
fs.mount.bin.uri = file:/proc/stat
```

**Comment by njuyuanrui** [comment]
I tried this:
```shell
fs.mount.stat.type = chroot
fs.mount.stat.path = /proc/stat
fs.mount.stat.uri = file:/proc/stat
```

and my python code like this:

```python
import sys
import os
#print sys.modules['psutil']

for filename in os.listdir(r'/proc'):
   	print filename
```

and the output:

```shell
meminfo
self
1
cpuinfo
``` 
It still cannot find the 'stat'
And I tried to read the /proc/stat directly , like this:

```python
f=open('/proc/stat', 'rb')
values = f.readline()
print values
```
output is a blank line
```shell

```
So I think the /proc/stat in LibOS is empty. It's confusing.

**Comment by donporter** [comment]
Graphene currently does not implement /proc/stat within the libOS.  I am curious why you need it?  If there is an application that requires this information, it would not be hard to add (although some fields would either need to be bogus, or would need a host ABI to expose correctly).  In general, we have added /proc files "on demand", or when we hit an application that we want to support that requires a given interface.

What you are doing with this manifest entry is creating a passthrough to the host /proc/stat, which might be ok, but it doesn't sound like what you want.

**Comment by adilahmad17** [comment]
Hi, sorry to intrude on this but I have a question. You said that 

``
fs.mount.stat.type = chroot
``
``
fs.mount.stat.path = /proc/stat
``
``
fs.mount.stat.uri = file:/proc/stat
``

creates a pass-through to the host's /proc/stat file. But that does not seem to be the case when I
try the same. It gives me an empty file. Is that expected behavior?

**Comment by donporter** [comment]
I suspect the issue is that /proc/stat reports its size as zero bytes, and graphene is checking this size before trying to read more bytes.

On my system: 

`$ ls -l /proc/stat 
-r--r--r-- 1 root root 0 Jun 19 22:17 /proc/stat
`

If there is a good reason to add /proc/stat, we can put this on the feature list, either for graphene-internal emulation or as a host pass-through.
