### ISSUE TITLE
epoll_socket problem sending requests

### ISSUE THREAD

**Issue by shmeni** [oscarlab/graphene#4]
My configuration is Ubuntu 14.04 64bit on an SGX-enabled i7 CPU with a graphene SGX-PAL.
[epoll_trace.tar.gz](https://github.com/oscarlab/graphene/files/417774/epoll_trace.tar.gz)

Reproduce:
Compile graphene with SGX support
go to native directory: make SGX=1; make SGX_RUN=1
./pal epoll_socket 8000

On another terminal:
telnet 8000

The telnet connects to the client, yet NO requests are sent to the client.

Attached a trace with debug=inline manifest

**Comment by chiache** [comment]
Hi,

This bug is fixed in the latest commit.
Reproduce the bugfixes:
1. Pull the latest code
2. Rebuild PAL and LibOS SHIM:
`cd Pal/src`
`make clean && make SGX=1`
`cd ../../LibOS/shim/src`
`make clean && make`
3. Rebuild the native test cases:
`cd ../test/native`
`make SGX=1 && make SGX_RUN=1`
4. Test the program:
`./pal epoll_socket 8000`
5. The program shall start to receive payload from client.

BTW, there is another issue that `epoll_wait` does not handle client-side shutdown properly and will spin forever (can be killed by Crtl-C). The behavior exists in Graphene on all platforms. This is a different bug and requires investigation.

**Comment by shmeni** [comment]
Much thanks, it is fixed on my machine as well
