### ISSUE TITLE
Basic file locking function support in LibOS

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#437]
The application which we are working on requires the file lock function with Graphene. 
Just the following pair of locking operations for `fcntl()` need to support, Thanks.

[F_SETLK](https://github.com/oscarlab/graphene/blob/8ca5eea1e1173bc6c06ec00f2851d4ee5e4e6189/LibOS/shim/src/sys/shim_fcntl.c#L170)
[F_GETLK](https://github.com/oscarlab/graphene/blob/8ca5eea1e1173bc6c06ec00f2851d4ee5e4e6189/LibOS/shim/src/sys/shim_fcntl.c#L195)

**Comment by donporter** [comment]
Completely reasonable request.  Probably not going to happen immediately, unless someone submits a PR, but will put it on the queue.

**Comment by debin-yang** [comment]
Copy issues from #1837 Need to give this production TODO task higher priority and start addressing it earlier instead of later. This is a blocking issue of Graphene to be used by the targeted usage which uses Spark and Graphene. Workaround is identified and can work temporarily only for POC of the usage but the workaround will not work for production of the usage.
