### ISSUE TITLE
Function "sock_getopt" is an empty function which always returns SUCCESS

### ISSUE THREAD

**Issue by rainfld** [oscarlab/graphene#467]
The function "sock_getopt" in Linux-SGX/sgx_enclave.c is an empty function where opt hasn't been filled but always returns 0 indicating opt has been filled successfully. This might cause potential issues. This function should be realized in future. 

static int sock_getopt(int fd, struct sockopt * opt)
{
    return 0;
}

**Comment by mkow** [comment]
Just an additional note: this may lead a caller to use uninitialized memory.

**Comment by mkow** [comment]
The bug with uninitialized memory was fixed some time ago, see:
https://github.com/oscarlab/graphene/blob/34b8eb1ec2b23d5538d8ede385eb1be50e29354d/Pal/src/host/Linux-SGX/sgx_enclave.c#L311-L319

We're now returning some hardcoded state, which I think isn't an issue per se because we can't trust the host anyways (also, this is _not_ the LibOS layer, so this isn't directly related to what `getsockopt()` syscall returns to the user app). So, I'm closing this issue. Feel free to reopen if you think something should be fixed here.
