### ISSUE TITLE
sgx_verify_report does not verify the report

### ISSUE THREAD

**Issue by HW42** [oscarlab/graphene#510]
[`sgx_verify_report`](https://github.com/oscarlab/graphene/blob/6bdd288a10e6ad64e567317c440fe4831a8a3fe1/Pal/src/host/Linux-SGX/enclave_framework.c#L77) currently does not verify the passed report. It just gets the key the report claims to be MAC-ed with and then does returns success. But it actually should calculate the MAC and check it.

Also it overwrites the global `enclave_key` variable which is otherwise used for trusted file verification. AFAIU this does not make sense.

**Comment by mkow** [comment]
Looks like valid issues. IMO we should finally introduce that `g_` prefixing for global variables, it makes issues like the latter much easier to spot.

Could you please relink `sgx_verify_report` from your comment to a particular commit from master, not just `master`? Otherwise it will quickly get outdated and become a dangling pointer ;)

**Comment by HW42** [comment]
> Could you please relink `sgx_verify_report` from your comment to a particular commit from master, not just `master`? Otherwise it will quickly get outdated and become a dangling pointer ;)

I wanted to do this anyway, but apparently I copied the link from the wrong tab ... ;]

**Comment by mkow** [comment]
> I wanted to do this anyway, but apparently I copied the link from the wrong tab ... ;]

hah :) looks good now, thanks!

**Comment by dimakuv** [comment]
This issue was fixed (among others) by Chia-Che in his own fork: https://github.com/chiache/graphene/blob/attest-proc/Pal/src/host/Linux-SGX/enclave_framework.c

Also see my Wiki explanation of a new fork protocol: https://github.com/oscarlab/graphene/wiki/Fork-Implementation-in-Graphene-SGX

The solution seems to be to wait for/ask Chia-Che to finish this work and submit a PR.

**Comment by HW42** [comment]
> This issue was fixed (among others) by Chia-Che in his own fork: https://github.com/chiache/graphene/blob/attest-proc/Pal/src/host/Linux-SGX/enclave_framework.c

Looks good on a first look. Will look more closely when there's a PR to review.

Even if the fix is still WIP it would be good to have issues for such known problems.

> Also see my Wiki explanation of a new fork protocol: https://github.com/oscarlab/graphene/wiki/Fork-Implementation-in-Graphene-SGX

Thanks for writing this up!

> The solution seems to be to wait for/ask Chia-Che to finish this work and submit a PR.

Yep.

**Comment by mkow** [comment]
> Even if the fix is still WIP it would be good to have issues for such known problems.

+1, we should keep this open until the fix lands on `master`.

**Comment by dimakuv** [comment]
This was fixed some time ago. See e.g. https://github.com/oscarlab/graphene/blob/1cb090d6dd9a49b70a85c1601fdd180e4ad48294/Pal/src/host/Linux-SGX/enclave_framework.c#L186. Closing this.
