### ISSUE TITLE
Cannot run sample code(LibOS/shim/test/native/futextest.pthread.c)

### ISSUE THREAD

**Issue by diwata11** [oscarlab/graphene#550]
When I run the sample code in this repo(LibOS/shim/test/native/futextest.pthread.c), a problem occure as follows.
""Cannot attach to any TCS!""

Is this the same problem as #517?

**Comment by dimakuv** [comment]
No, it's not the same problem.

This error message indicates that you need to increase the number of threads available to Graphene-SGX. If you look into an auto-generated `futextest.pthread.manifest.sgx` (in the same directory as sample code), you will notice: `sgx.thread_num = 4`. There are only 4 threads available to create for SGX.

If you look at the code of `futextest.pthread.c`, you will notice that 4 threads are created in it (1 main thread + 3 additional threads). In addition, Graphene-SGX creates a couple helper threads (Async Helper and IPC Helper).

So, for this particular code, you need to specify at least 6 threads in the manifest. Since manifests are generated from a single file `manifest.template`, you need to add a line in this file: `sgx.thread_num = 6` and rebuild this code (the easiest is to `make SGX=1 clean && make SGX=1 && make SGX_RUN=1`).

After you built it, you will notice that the newly generated `futextest.pthread.manifest.sgx` contains 6 SGX threads now. And if you run the program itself, it will execute correctly.

P.S. Why maximum of 4 SGX threads by default? No specific reason, it just worked for most applications. You can see this default value added to auto-generated manifests in `Pal/src/host/Linux-SGX/signer/pal-sgx-sign` (search for `DEFAULT_THREAD_NUM`). If you change this value to `6`, it will also work.

**Comment by yamahata** [comment]
https://github.com/oscarlab/graphene/pull/552 for more friendly message on what to do.

**Comment by diwata11** [comment]
Thank you for the response!
This problem is solved by changing manifest.template.

I really appreciate your cooperation.
