### ISSUE TITLE
file operation not work at python with SGX

### ISSUE THREAD

**Issue by Yourens** [oscarlab/graphene#60]
Hello there,    
I'm new for Graphene, I just build graphene on SGX.    
Firstly I go to Libos/shim/test/apps/python and add those lines to python.manifest.template   
```    
 fs.mount.storage.type = chroot
 fs.mount.storage.path = /storage
 fs.mount.storage.uri = file:/home/shenyouren/storage
```    
Then I run      
```
make SGX=1
make SGX_RUN=1
```

After that I modify script/helloworld.py and want to chdir to /storage.
But the python code     
```
os.chdir("/storage")
```
returns   
```
OSError: [Errno 20] Not a directory
```
I tried to change to other dir like /bin /host but failed too except /usr  

I don't know why and can't figure out what's the different between /usr and other chroot entries.
  
Would you mind to help me?  

Really appreciate for reply!    
Thank you very much.

**Comment by donporter** [comment]
Hi @Yourens,

I'm guessing you have either fixed this issue or moved on.  This does not seem like the expected behavior, and it seems you are doing this correctly.

If you need more help, please attach the manifest file that is giving you problems, as well as the complete output, and any other steps to reproduce.  

Even better, compile with 'DEBUG=1' and set the debug type to 'inline' in your manifest, and share the complete output.

I'm going to close this issue for now, but feel free to reopen it if you are still having problems.
