### ISSUE TITLE
Is it possible to keep the unmodified Applications outside SGX while the libraries inside SGX?

### ISSUE THREAD

**Issue by heartever** [oscarlab/graphene#61]
While it is amazing to keep both the unmodified application binary and supporting libraries inside SGX, sometimes when the applications are not trusted we may only want to isolate (some of) the libraries inside an SGX enclave. Is it possible, for example based on a minimum modification of graphene-SGX? I am having this question, as sometimes we don't need to protect the entire address space. Thanks.

**Comment by 0xhwang** [comment]
of course you can do this by extend more ecalls, or just use intel's sgx sdk.

**Comment by heartever** [comment]
Yeah, I like the features of porting unmodified binaries, so I will not opt for the official sdk. So it's viable to  only load the supporting libraries inside SGX, I guess?

**Comment by heartever** [comment]
I read from the graphene-SGX paper in Usenix ATC. I am glad to know in the paper that graphene-SGX supports partitioning the application and running smaller pieces of code, such as a library, in an enclave. Could anyone explain the way for doing this? For example, I have a normal application calling functions in a library. How can I put the library into SGX without changing much of the application code? Thanks

**Comment by chiache** [comment]
Hi, while the concentration of Graphene-SGX in this stage is to support unmodified applications,
one can always use Graphene-SGX as a supporting framework for running a library or a piece of partitioned code, if he/she is willing to pay a little more programming effort. In other words, Graphene-SGX can support and protect the OS functionality needed by the code running inside the enclave, while the protected code can export a separate enclave interface, such as the library APIs.

Although there is no official way of doing this, here are the potential steps to partition an application and run it with Graphene-SGX:

1. Partitioning the code into a separated, executable binary.  If the isolated code is the whole library, turn the library into a position-independent executable (some tweaks in the compilation options should make this happen). The library may require a fake entry point (the main function) if it does not already have one.

2. Design your enclave interfaces, and integrate with the existing Graphene-SGX enclave interfaces. For each of your enclave interfaces, design a reasonable checking/shielding mechanism, including copying the arguments into the enclave before executing the code.

3. Extend Graphene-SGX to export a set of new host interfaces, to link the symbols in the partitioned code or the library, to the enclave interfaces you added, so that the execution knows where to jump after entering the enclave through the enclave interfaces.

Supporting partitioned application is not a built-in feature of Graphene-SGX, but we have experimented the possibility, given some development effort. We will consider adding this as a usability feature in the future.
