### ISSUE TITLE
accept(tcp_socket, ...) and SIGCHLD at the same time

### ISSUE THREAD

**Issue by alsroad** [oscarlab/graphene#624]
Hello, I'm using graphene with Intel SGX.
I wrote a simple TCP server code with fork() as follows.

while(1){
   connfd = accept(serverfd, ...);
   pid = fork();
   if (pid > 0){ // parent
     write(pipefds[1], );  
   }
  else if (pid == 0) { // child
     read(pipefds[0], );
     send_reseponse();
     exit(1);
  }
}

Whenever the server accepts a connection, it forks and the parent process sends some messages to the child process.
Then, the child reads the messages, then responds to the client (who is not graphene).

Actually, the program who is blocked in **accept()** fails when it receives **SIGCHLD**.

The code works normally when I add 'waitpid' before accept().

How can I fix it? Thanks in advance.

**Comment by yamahata** [comment]
When signal arrives during ocall in untrusted code, the ocall result becomes unconditionally PAL_ERROR_INTERRUPTED regardless to the actual requested system call is really issued or successfully completed or EINTR.
The right fix is, track if the actual host system call result(or not issued yet) and make ocall return both syscall result and external exception.

**Comment by dimakuv** [comment]
You can try this PR: https://github.com/oscarlab/graphene/pull/618 which fixes the issue that @yamahata explained. This PR is a "band aid" but works in most cases.

In the future, SGX signal handling will be re-written to be stable. Please ping us if this PR doesn't help and send more info (your C code, your log).

**Comment by parkminkyung** [comment]
Thanks for your fast feedback. 

Actually, the PR didn't resolve the problem.

Currently, the program is exited with the error code in the graphene-SGX, but normal execution (in host OS) shouldn't be terminated.

For more information, I attach the code (server.libos.c) and log file. 
The program terminates with the message "DkProcessExit: Returning exit code 1", but it isn't shown in the log. (I used > command).

[client_agent.c.txt](https://github.com/oscarlab/graphene/files/3097098/client_agent.c.txt)
[output_log.txt](https://github.com/oscarlab/graphene/files/3097093/output_log.txt)
[server.libos.c.txt](https://github.com/oscarlab/graphene/files/3097094/server.libos.c.txt)

Thanks again.

**Comment by dimakuv** [comment]
Ok, this one was pretty simple to figure out.

Your server code doesn't correctly handle the case of `accept()` returning `-EINTR` (interrupted syscall):
```c
connfd = accept(serv_socket, (struct sockaddr *)&cli, &len);
if (connfd < 0){    // <--- fail program even on EINTR!
	perror("server accept failed..."); 
	exit(1); 
}
```

The problem is that Graphene-SGX doesn't support `SA_RESTART` flag for slow system calls (not yet; this support will be added in future). This flag is optional for POSIX systems, so your application should actually have a error handler for this case:
```c
connfd = accept(serv_socket, (struct sockaddr *)&cli, &len);
if (connfd < 0){
	if (connfd == -EINTR) {
		/* accept was interrupted by signal SIGCHLD, need to restart accept! */
	}
	perror("server accept failed..."); 
	exit(1); 
}
```

Note that Linux supports `SA_RESTART` and transparently restarts `accept()` after the signal from your child process. That's why on host Linux you saw different, "normal" behavior.

More info here:
* http://man7.org/linux/man-pages/man2/accept.2.html
* https://stackoverflow.com/questions/23685816/why-doesnt-linux-accept-return-eintr
* http://alas.matf.bg.ac.rs/manuals/lspe/snode=87.html
