### ISSUE TITLE
Child can't connect to a UNIX domain socket created by parent.

### ISSUE THREAD

**Issue by smherwig** [oscarlab/graphene#675]
If a parent creates a UNIX domain socket, Graphene does not create a host file for the socket.  Thus, when the child tries to connect to the socket, the call to `path_lookupat` in `shim_do_connect` will fail, returning `-ENOENT`.

**Comment by dimakuv** [comment]
Sorry, this description is a bit too dense. Could you give more details?

**Comment by smherwig** [comment]
Graphene mangles UNIX domain sockets (perhaps for isolation between two Graphene process-trees).  The mangling for a name of `/tmp/foo.sock` is basically `\0x00/graphene/some-id/hash(/tmp/foo.sock)` -- that is, the first byte is 0, making it an abstract socket.  Graphene never actually creates a file.  That is, for a writeable chroot fs, Graphene does not create a file on the untrusted host system.  The child connects to the socket by specifying the path.  The path lookup does not take into account the name mangling, looks on the chroot fs, sees that the file does not exist, and returns `-ENOENT`.

**Comment by dimakuv** [comment]
Got it. So the correct solution is to make the path lookup aware of the name mangling? Or do you need to create an underlying file for you case (i.e., the fact that Graphene creates an abstract socket is a bug)?

**Comment by dimakuv** [comment]
The issue was abandoned, but it looks like the issuer wanted to connect a Graphene instance with some non-Graphene instance. This is impossible in Graphene model.

UNIX domain sockets work fine, we have a test for them: https://github.com/oscarlab/graphene/blob/4cb98219d8e302055587a8952c1102415a72ba42/LibOS/shim/test/regression/unix.c#L1

This test also has a top-level comment saying that only two processes in the same Graphene instance may communicate.
