### ISSUE TITLE
[LibOS][SGX]  test_user_memory issue

### ISSUE THREAD

**Issue by Lu-Biao** [oscarlab/graphene#747]
I have some code to test getcwd, but 'getcwd' will return NULL, and the errno is EFAULT
```
static char cwd_buf[PATH_MAX];

int test_getcwd()
{
    char *cwd = NULL;

    cwd = getcwd(cwd_buf, sizeof(cwd_buf));
    if (cwd) {
        std::cout << "getcwd: " << cwd << std::endl;
        return 0;
    }
    std::cout << "getcwd errno: " << errno << std::endl;

    return -1;
}
```
The buffer address passed to 'getcwd' is 0x6021c0, and the buffer size is 4096.
```
[     1] ---- shim_getcwd(0x6021c0,4096) = -14
```
It seems that the start and end of the buffer are in two vma:
```
[0x602000-0x603000] prot=00000003 flags=00000012 uri=file:hello offset=8192
[0x603000-0x604000] prot=00000003 flags=00000032 offset=0
```
so test_user_memory return false.

**Comment by donporter** [comment]
Thanks for the report!

**Comment by dimakuv** [comment]
Thanks for the bug report. The issue is that DATA and BSS segments are adjacent to each other (on my machine, your code has DATA.end = 0x601048 and BSS.start = 0x601048, so on the same page). Graphene-SGX tries to separate DATA and BSS and aligns these segments by page-size. Thus, in my case DATA is in the range (0x600000, 0x602000) and BSS is in the range (0x602000, 0x603000).

Looking at the code, I don't see a need to separate DATA and BSS in two VMAs. One solution is to lump these two sections together (since the current code incorrectly divides them anyhow). I will submit a PR fixing this.

**Comment by dimakuv** [comment]
Per discussion with Chia-Che, it is actually better to change `test_user_memory()` to understand adjacent VMAs. In theory, there can be a buffer spawning two VMAs, and our code should correctly handle such cases.

**Comment by dimakuv** [comment]
I created PR #748. Please test it with your test case and report back if the bug is fixed.

**Comment by Lu-Biao** [comment]
> I created PR #748. Please test it with your test case and report back if the bug is fixed.
I have tested 'PR #748', it works well. Thank you.
