### ISSUE TITLE
chown/fchownat are no-ops

### ISSUE THREAD

**Issue by donporter** [oscarlab/graphene#787]
Our implementation of chown/fchownat don't do anything with uid, gid, and flags (fchownat).

**Comment by chiache** [comment]
Because our library OS has its own virtualized uid and gid, it doesnt make whole lot of sense to propagate the result of chown/fchownat to the host. Supposedly a malicious program sets an executable with uid 0 or makes it a seteuid program, this can be a vulnerability for our sandboxing system.

On the other hand, either uid nor gid is platform-independent. For instance, Windows doesn't use the uid/gid system like Linux/BSD. I suggest we approach this implementation with caution, and prioritize use cases that we actually care about. 

That being said, is there a specific reason that you want to propagate chown/fchownat?

**Comment by donporter** [comment]
Just logging the issue.  Won'tfix is a fair outcome.

**Comment by dimakuv** [comment]
This is still valid on current master: https://github.com/oscarlab/graphene/blob/f1a9c785128522ae4abc604a7ae10f4d4e7f0573/LibOS/shim/src/sys/shim_file.c#L239

I actually prefer to close this issue. We don't care about file permissions. Pawel, feel free to re-open if you think this is important.
