### ISSUE TITLE
Observed a hang when I run R and busybox application on graphene SGX

### ISSUE THREAD

**Issue by Gautham103** [oscarlab/graphene#815]
Observed hang when I run R application on graphene SGX. I used `make SGX=1` and `make SGX_RUN=1` to compile R application.

```
R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/lib/R/library/stats/libs/stats.so':
  /lib/libm.so.6: version `GLIBC_2.23' not found (required by /usr/lib/x86_64-linux-gnu/libquadmath.so.0)
During startup - Warning messages:
1: package 'stats' in options("defaultPackages") was not found 
2: Setting LC_CTYPE failed, using "C" 
3: Setting LC_COLLATE failed, using "C" 
4: Setting LC_TIME failed, using "C" 
5: Setting LC_MESSAGES failed, using "C" 
6: Setting LC_MONETARY failed, using "C" 
7: Setting LC_PAPER failed, using "C" 
8: Setting LC_MEASUREMENT failed, using "C" 
> print(sample(1:3))
[1] 2 1 3
> print(sample(1:3, size=3, replace=FALSE))  # same as previous line
[1] 3 2 1
> print(sample(c(2,5,3), size=4, replace=TRUE))
[1] 3 2 3 5
> print(sample(1:2, size=10, prob=c(1,3), replace=TRUE))
 [1] 2 2 2 2 2 2 2 1 2 1
> 
WARNING: no physical memory support, process creation may be slow.
cannot open manifest file: sh.manifest.sgx
USAGE: /home/grads/g/gautham_srinivas/graphene/Pal/src/../../Runtime/pal-Linux-SGX [executable|manifest] args ...
```
Observed hang when I run busybox application on graphene SGX. I used `make SGX=1` and `make SGX_RUN=1` to compile busybox application.

```
./busybox.manifest.sgx sh
```

Both these issues are reproducible 100%.

**Comment by dimakuv** [comment]
Thanks for the bug report. There are a couple of issues with R in your example:

1. `/lib/libm.so.6: version `GLIBC_2.23' not found` -- one of R's libraries complains that it cannot find Glibc functions of version 2.23. This is fare because Graphene currently has an internal Glibc version 2.19. We have a PR to fix this: https://github.com/oscarlab/graphene/pull/809. This PR will soon be merged, and this particular issue will disappear.

2. `cannot open manifest file: sh.manifest.sgx` -- do you have this file? Was it created as part of the R build process? What happens is that R tries to execute the `sh` process (the Linux shell) but cannot find its Graphene manifest. You can probably create this file manually and then re-run R.

We'll have to look into busybox. I don't think anyone tested it as of lately.

**Comment by mkow** [comment]
Both examples were rewritten since then, closing as outdated.
