### ISSUE TITLE
Re-enable kill12 after updating glibc version

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#873]
It seems that because of a bug in the old glibc we use, kill12 test from LTP sometime fails. It will be soon disabled by https://github.com/oscarlab/graphene-tests/pull/18.

We should re-enable it after merging #809.

**Comment by mkow** [comment]
Update: We dropped glibc 2.19 but this test still doesn't work for me, even without SGX. It just timeouts without printing anything.
@yamahata Could you take a look at this? You debugged the original issue, so you probably have more insight here.

**Comment by yamahata** [comment]
Okay, I dug it a bit. Here's what's happening.
glibc 2.19 issue is removed. So sigchld issue is solved.
But we're hitting other issues. race conditions.ENTER_PAL_CALL, LEAVE_PAL_CALL[_RETURN].
 
So they needs to be addressed somehow.
  (My understanding of) The design of PAL invoking LibOS signal handler is 
  - if it was not executing PAL, invoke LibOS signal handler: This case is okay.
  - if it was executing PAL, queue the signal to PAL TCB and invoke LibOS signal handler by LEAVE_PAL_CALL which checks if there are queue signals. and PAL call may results in -EINTR.
(note: the boundary of PAL and LibOS needs to be defined more properly. IN_PAL($rip) is too simple in this case.)

- Pal/Linux case
  there is a race so that even if PAL queues the signal, it doesn't invoke LibOS signal handler.
  the signal can arrive after LEAVE_PAL_CALL, but still in PAL code.
  In this case, kill from one process/thread to another process/thread is missed.

- Pal/Linux-SGX
  There is also a race. Pal can aborts PAL call (by pal frame) or invokes LibOS signal handler (if outside of ocall. remember the changeset of c6622ba12e6fc469a4cd5c3d3200c421535c3308). 
   In either case, It can break the data integrity of PAL. Please notice that PAL can be executing internal malloc or PAL can issue multiple ocalls for single PAL call.

**Comment by yamahata** [comment]
#1202 
#1203 

I think there still remains other races, though.

**Comment by mkow** [comment]
Thanks!

btw. We should remember to remove the note about this from LTP readme after re-enabling the test.

**Comment by mkow** [comment]
This test was enabled some time ago, closing.
