### ISSUE TITLE
Support for glibc >= 2.29 ?

### ISSUE THREAD

**Issue by bgrieder** [oscarlab/graphene#941]
I know there are already few issues mentioning the use of glibc 2.19 and "somewhat compatible" support for glibc up to 2.27.

However it is hard to gather from these threads whether support for glibc 2.29+ is on the roadmap at all and at what horizon.

This would allow moving to Ubuntu 18.04 (and 19), and would greatly facilitate development [on developer machines]. Intel SGX driver and SDK already work well on these system versions. 

Could you please shed some lights on plans if any ?

( a straight upgrade of libm does not seem to create any issue whatsoever)

**Comment by donporter** [comment]
Thanks for the interest!  We have a short-term goal of supporting Ubuntu 18.04, and it seems 2.27 is sufficient for this goal.

In the longer term, we are pursuing upstreaming changes to glibc, rather than patching future versions.

We don't have a specific timeline for patching/debugging/testing newer glibc versions, and probably want to bound our effort with debugging and testing the latest versions. With a particular need for a newer glibc, we might prioritize it, or accept patches ported to this version.

**Comment by yamahata** [comment]
#912 and  #915

**Comment by bgrieder** [comment]
Thanks

**Comment by dimakuv** [comment]
@bgrieder We recently merged support for Glibc 2.31. If you're running Ubuntu 18.04 or higher, Graphene will automatically use Glibc 2.31. See https://github.com/oscarlab/graphene/pull/1369.

I'm closing this issue since it was resolved.
