### ISSUE TITLE
Verify parent mrenclaves in child process

### ISSUE THREAD

**Issue by chiache** [oscarlab/graphene#972]
When creating processes on SGX, the parent and child processes should verify each other's measurements (mrenclaves). Currently, we only check child mrenclaves in the parent processes, but have no check for the other way around.

However, it is unclear what's the appropriate way of checking the parent measurement in the child process. Listing the parent's mrenclave in the child's manifest will fall into a loop of updating the parent's and the child's manifest files alternatively. Potentially, we may consider using a crypto challenge instead of listing the mrenclaves directly.

**Comment by dimakuv** [comment]
One simple way (and arguably the only way that makes sense?) is to check MRSIGNER of the parent -- the parent must have the same MRSIGNER (+ ISVPRODID + ISVSVN) as the child.

We will also need another policy for the parent to check the child -- not only using MRENCLAVE as we do currently, but also checking via MRSIGNER + ISVPRODID + ISVSVN.

**Comment by mkow** [comment]
This will be fixed by #2050, but not in any of the ways proposed here. There's actually no need to verify the parent, only the parent needs to verify children, as only the parent contains any secrets. The secrets will be provisioned from the parent to the child only after successful local attestation.
